Adhering o coding conventions (partially)
runtimeverification/vlsm pull request #111
Opened 2022-09-22 14:00 UTC by DafinaTrufas

2022-09-22 17:41 UTC, wkolowski requested changes

2022-09-22 17:41 UTC, wkolowski commented on theories/VLSM/Core/AnnotatedVLSM.v
> +  * State-annotated VLSMs
@DafinaTrufas This is wrong, as you shouldn't treat section headers like ordinary comments. The same goes for subheaders (`**`), subsubheaders (`***`) etc.

2022-09-22 17:42 UTC, wkolowski commented
@DafinaTrufas Besides fixing the section headers, maybe you should write some comments for the awk script.

2022-09-23 14:03 UTC, wkolowski commented on scripts/out.log
> +*)
What is this file doing? Looks like it should not be committed.

2022-09-23 14:03 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +  The second fixed byzantine trace definition.
@traiansf Hmm, looks like this one should be a section header.

2022-09-26 09:31 UTC, traiansf reviewed
Seems there is still some work left with detecting endings where there is no space before `*)`, e.g., `**)` or things like `.*)`

2022-09-26 09:31 UTC, traiansf commented on theories/VLSM/Core/Composition.v
> +   component i.
maybe here it's not necessary to break line as we're in a regular comment.

2022-09-26 09:31 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +      build some generic definitions first. **)
Or maybe we need to bother with them :-)

2022-09-26 09:46 UTC, palmskog reviewed
Some initial comments to consider, mostly I agree with @traiansf.

2022-09-26 09:46 UTC, palmskog commented on theories/VLSM/Core/Composition.v
> +
Right, this newline should be avoided.

2022-09-26 09:46 UTC, palmskog commented on theories/VLSM/Core/Composition.v
> +
Another newline that should be avoided.

2022-09-26 09:46 UTC, palmskog commented on theories/VLSM/Core/Composition.v
> +   component i.
I agree, I think we should leave regular comments (starting with only `(*`) unaffected.

2022-09-26 09:46 UTC, palmskog commented on theories/VLSM/Core/Equivocation.v
>  **)
Ah, we should never end a comment with `**)`, maybe a script can fix this?

2022-09-26 09:46 UTC, palmskog commented on theories/VLSM/Core/Equivocation.v
> +  Lemma selected_message_exists_in_all_traces_initial_state
Not sure what's going on here, but maybe best if we leave regular code (outside of comments) alone with the script? Otherwise, it's going to be harder to review.

2022-09-26 13:43 UTC, wkolowski requested changes
Lots of faults.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces.v
> +  in the second,
I'd say the second line of this should be indented more, but this is not a fault introduced by the script.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation/MsgDepLimitedEquivocation.v
> +      other that the message sender.
Too much indentation.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation/NoEquivocation.v
> +      to be received [has_been_sent] previously in the state about to receive it.
Again.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation/TraceWiseEquivocation.v
> +      which does not verify the order in which receiving and sending occurred.
Not sure if I'm right, but this one is indented too much, isn't it?

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation/TraceWiseEquivocation.v
> +      Note that this definition does not require the [HasBeenSentCapability].
Again.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +  Qed.
A whole lemma got indented!

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +*)
A double `(**`.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
>    (s : composite_state)
A now it seems everything after that double `(**` is commented out, leading to parse errors.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +     The equivocation fault sum: the sum of the weights of equivocating
@palmskog @traiansf @bmmoore Should doc comments be allowed to appear inside a `Class` definition? I think it makes more sense to have normal comments instead and a big doc comment at the top for the whole class.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      build some generic definitions first.
Too much indentation.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      The [message_selector] argument specifies whether we're looking for received or sent
Again.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      with a [state_message_oracle] for sent messages have the [has_been_sent] capability.
Again.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      Furthermore, we require a [sent_excluded_middle] property, which stipulates
And again...

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +  'pre_loaded_with_all_messages_vlsm'
That's not a matter of the script, but the names here are improperly quoted (should be `[]` instead of `''`).

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +  (avoiding 'pre_loaded_with_all_messages_vlsm')
Again.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      will have [has_been_sent] and [has_been_received] capabilities.
It seems this one was badly indented from the beginning.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +  A message 'has_been_received' for a composite state if it 'has_been_received' for any of
Another improperly quoted name.

@traiansf Maybe we should have another PR for this?

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      of a certain message, then it is impossible for other components
Bad indentation.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +       slightly weaker, in that it does not require that the sender
Again.

2022-09-26 13:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      our is_equivocating property is decidable. The current implementation
Again...

2022-09-27 09:05 UTC, palmskog reviewed
This now looks quite good, but there are still two high-level issues:
- non-coqdoc comments (that do not begin with `(**`) are getting processed, while they should actually be ignored.
- some comments get too much indentation

2022-09-27 09:05 UTC, palmskog commented on theories/VLSM/Lib/ListExtras.v
> +*)
Ah, this is another instance of a non-coqdoc comment.

2022-09-27 15:50 UTC, traiansf commented on theories/VLSM/Core/ByzantineTraces.v
Probably it would be better to do it in a subsequent PR, but it would be nice to have a script removing extra blank lines ar the beginning and end on coqdoc comments.

2022-09-27 15:50 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +*)
this one is left unindented.

2022-09-27 15:50 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +      Notably, we also define the [has_not_been_sent] oracle, which decides if a message
this one is indented too much; maybe we need an extra state for that automaton.

2022-09-27 16:13 UTC, DafinaTrufas commented
I also noticed that there are still non-coqdoc comments modified by the script, so I'm trying to change the approach there.

2022-09-28 11:53 UTC, traiansf approved these changes
Looks good to me!

2022-09-28 11:53 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +  We now move on to a composite context. Each component of our composition
To be fixed in subsequent PRs.

2022-09-28 11:53 UTC, traiansf commented on theories/VLSM/Core/Validator.v
> +  ** Direct definition of induced validator from composition to component
Not a fault of this script, but this line needs to be merged into the previous.

2022-09-28 13:25 UTC, wkolowski approved these changes
Looks pretty good.

2022-09-28 13:25 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +*)
Not a fault of the script, but this looks suspicious.

2022-09-28 13:25 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +  *** The type of a VLSM
@palmskog @bmmoore @traiansf Is it even legal to put subheaders in places like this?

2022-09-28 13:25 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +  The tactical <<split;[constructor;apply initial_state_is_valid|];assumption>>
Mentioning `assumption` in the comment seems outdated, as we don't use `assumption` anymore.

2022-09-28 13:25 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
>  (** *** valid traces
The header should probably start with an uppercase letter.

2022-09-28 13:25 UTC, wkolowski commented on theories/VLSM/Lib/ListSetExtras.v
> +  because <<length>> of <<filter>> can be simplified
Not related to this PR, but

```suggestion
  because [length] of [filter] can be simplified
```

2022-09-28 15:58 UTC, bmmoore commented on theories/VLSM/Core/VLSM.v
> +  *** The type of a VLSM
Yes. The start of a coqdoc comment isn't treated differently, it just translates any markup inside.

2022-09-28 16:00 UTC, bmmoore commented
Maybe this should actually include non-coqdoc comments? If we have a style for multiline comments we should probably also follow it for non-coqdoc comments.

2022-09-29 07:53 UTC, palmskog commented
My view: best to skip modifying regular comments this time. But we should think about whether we *should* have regular comments and for what. For example:

- only use regular comments for one-liners
- only use regular comments inside proofs to explain proof steps or for dev-internal communication (TODO, gotcha, etc.)

2022-10-03 13:18 UTC, merged