Standardize the use of finishers across the VLSM codebase
runtimeverification/vlsm pull request #132
Opened 2022-10-27 19:01 UTC by wkolowski

I made sure that all subgoals end with the use of `by`, refactoring some proofs as I went along.

Also with @bmmoore we agreed that we should write `by congruence`, `by itauto` even though `congruence` and `itauto` are succeed-or-fail style tactics.

Similarly we should also write `by firstorder`.

2022-10-27 22:51 UTC, bmmoore commented
Reading the coding convention more carefully, I see it doesn't actually require `by congruence`. I was only complaining about using `itauto` without `by` because I mistakenly thought we were requiring `by` on `congruence` and nobody who instantly recognizes `itauto` as a finisher would be unfamiliar with `congruence`.

If we allow `congruence` as a finisher I don't necessarily mind the current state. But maybe if we hope to have readers unfamiliar with Coq maybe we should just completely standardize on `by` and `done`.

I can review this PR assuming the new policy.

But I would like @palmskog's (and @traiansf's if available) opinion on the style.

2022-10-28 14:29 UTC, wkolowski commented
@bmmoore Regarding finishers, I wanted to make sure that every proof and every subgoal is finished with `by` and that when we are using `; [ | ]` it is clear whether the given subgoal is solved (in which case `by` appears) or not. I changed to `by congruence` and `by itauto` everywhere, so please review with that in mind. In case we don't want it, it'll be easy to find-and-replace.

2022-10-31 12:31 UTC, palmskog reviewed
I think there are two types of changes here, and I would prefer to see the former split out into a separate PR that can be merged quickly:
1. adding missing `by` finishers, e.g., for `firstorder` and so on
2. other changes that involve chaining tactics that were previously unchained and so on

I'm *not* on board with the second kind of changes. I can see no obvious gain from merging certain kinds of sentences. For example, having many tactics per line can in many cases just make proof failures harder to debug.

2022-10-31 12:31 UTC, palmskog commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +    by revert Ht; apply @induced_sub_projection_transition_preservation.
I don't really understand this refactoring - it doesn't make the proof easier to follow (in fact harder). Why wouldn't a single-line `revert` be allowed?

2022-10-31 12:33 UTC, palmskog commented on theories/VLSM/Core/ELMO/ELMO.v
> +      by unfold Message; rewrite elem_of_cons; firstorder congruence.
Another example of a change that makes no sense to me, and I think doesn't have much to do with the topic of the PR.

2022-10-31 15:30 UTC, bmmoore commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +    by revert Ht; apply @induced_sub_projection_transition_preservation.
I think it makes more sense to consider `revert H; apply lem` as a unit - I understand it as "apply lem with H as some(or the penultimate) argument", and short for some `apply (lem _ ... _ H)`, or being a plain-tactics version the ssreflect `apply: lem H`.

But I agree this sort of change doesn't fit the overall aim of the PR, and that chaining more tactics isn't always an improvement.

2022-10-31 15:34 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +    by revert Ht; apply @induced_sub_projection_transition_preservation.
@bmmoore is right - the only purpose of this `revert` is to make it possible to use the following `apply`, so they should be considered as a unit. And since the following `apply` finishes the proof, it gets touched in the PR, so I think it is in scope of this PR.

2022-11-02 08:12 UTC, palmskog requested changes
@wkolowski after discussing with @traiansf I'd like to explicitly request a split PR here. Please restrict this PR to only doing the minimal changes to add finishers (without combining tactic sentences unless it's completely unavoidable), and do a different PR with other tactic changes.

2022-11-02 14:50 UTC, bmmoore commented on theories/VLSM/Core/ELMO/ELMO.v
> +      by unfold Message; rewrite elem_of_cons; firstorder congruence.
I don't see how that affects what should be joined with `;` or `.`. In that sense I would say everything after the `+` is instructions for finishing the proof, and it wouldn't work to say any bullet without sub-bullets should all be chained together.
I think the major questions are what makes sense to think of as conceptually single or similar steps, and where a reader might want to pause and view the proof state.

Any sequence of `unfold`, `rewrite`, and simplification tactics is usually a reasonable unit because it always produces a goal that should be equivalent to the original. And it's a natural place to step back and forth and check if you follow the equivalence or need to look up definitions - which is much easier if you can actually look at the term afterwards, instead of having to imagine it.

While `firstorder congruence` means "it may not be immediately obvious, but this is a (first-order+equality) tautotology". So it's not the same sort of thing.

2022-11-02 14:59 UTC, bmmoore commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +    by revert Ht; apply @induced_sub_projection_transition_preservation.
I'm defending it as good refactoring, but I don't think it's necessary for fixing nonstandard usage of `by` if we're splitting the PR now.

I see nothing incorrect about the usage of `by` with the `apply` in the old code. It's certainly a line you would have to inspect to check if finishers were used correctly everywhere, but I don't think it needed to be changed.

2022-11-03 14:12 UTC, wkolowski commented on theories/VLSM/Core/ELMO/ELMO.v
> +      by unfold Message; rewrite elem_of_cons; firstorder congruence.
My current philosophy is that each line should only contain a single atomic logical step, which can be composed out of many tactics with `;`. Bureaucracy and finishers are not atomic logical steps, so they should be joined to the really important part with `;`. So as I said, in this example the core is the `rewrite`, the bureaucracy is the `unfold` and `by` and `firstorder congruence` are the finisher, so I think it makes sense to chain them.

2022-11-03 14:15 UTC, wkolowski commented
I will try to filter this PR to only contain the changes you are asking for. Recently I learned about `git add --patch` - let's see how much it can do here.

2022-11-03 15:22 UTC, bmmoore reviewed
The changes I've checked seem to okay either as fixing a finisher, or an acceptable refactoring that doesn't fix a finisher, but if those categories will become separate PRs I will wait until it is split.

2022-11-03 18:43 UTC, wkolowski commented
@palmskog @bmmoore Please review and tell me if it's better now. I tried to remove the changes that Karl didn't like from this PR using `git add --patch`, but some may have been overlooked. Also I'm afraid that the other refactorings might be gone, as I forgot to save them somewhere before I did `git push --force`.

2022-11-09 10:55 UTC, palmskog reviewed
This looks a whole lot better now, but please address my remaining comments in some way. If that's done, I'm prepared to approve this.

2022-11-09 10:55 UTC, palmskog commented on theories/VLSM/Core/Equivocation.v
> +  by firstorder.
`firstorder` is not really considered a good tactic anymore (it's barely maintained), so I disagree that this is an improvement. However, it's a very minor occurrence in the grand scheme of this PR.

2022-11-09 10:55 UTC, palmskog commented on theories/VLSM/Core/Equivocation/WitnessedEquivocation.v
> +      spec IHn; [by split; [| done]; apply finite_valid_trace_from_to_forget_last in Htr' |].
I disagree that this is an improvement. The previous formulation is much easier for debugging failing proofs.

2022-11-09 10:55 UTC, palmskog commented on theories/VLSM/Core/Equivocation/WitnessedEquivocation.v
> +    destruct iom as [im|]; [| by repeat split; [| apply option_valid_message_None | ..]].
This has now become a very deeply nested goal structure. Would be better to actually introduce bullets so we can keep the separate goal from previously.

2022-11-09 10:55 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/FixedEquivocation.v
> +  spec Hitem_equivocating; [by subst; rewrite !elem_of_app; right; left; left |].
I disagree that this is an improvement, again for reason of more difficult proof debugging.

2022-11-09 10:55 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/FixedEquivocationSimulation.v
> +    destruct iom as [im |]; [| by exists [], eqv_state_s; split; [constructor |]; eauto].
Like a similar comment elsewhere, this is not an improvement to me.

2022-11-09 10:55 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/SimulatingFree/SimulatingFree.v
> +    destruct iom as [im |]; [| by exists [], eqv_state_s; split; [constructor |]].
Same non-improvement pattern as elsewhere.

2022-11-09 10:55 UTC, palmskog commented on theories/VLSM/Core/VLSM.v
> +    by firstorder.
As elsewhere, I don't think this is an improvement. Can't `itauto` be a replacement somehow?

2022-11-09 10:55 UTC, palmskog commented on theories/VLSM/Lib/StreamExtras.v
> +  by firstorder.
As usual, I don't think this is a gain. Changing to use `itauto` would be.

2022-11-09 13:49 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +  by firstorder.
Maybe leave getting rid of `by firstorder` for a separate PR? I checked and `itauto` doesn't work here.

2022-11-09 13:51 UTC, wkolowski commented on theories/VLSM/Core/Equivocation/WitnessedEquivocation.v
> +      spec IHn; [by split; [| done]; apply finite_valid_trace_from_to_forget_last in Htr' |].
Ok, I reverted it back. But what about

```suggestion
      spec IHn; [by split; [apply finite_valid_trace_from_to_forget_last in Htr' |] |].
```

Do you think it is just as bad?

2022-11-09 13:56 UTC, wkolowski commented on theories/VLSM/Core/Equivocation/WitnessedEquivocation.v
> +    destruct iom as [im|]; [| by repeat split; [| apply option_valid_message_None | ..]].
What about

```suggestion
    destruct iom as [im |]; [| by repeat split; auto using option_valid_message_None].
```

It would be sad to introduce bullets, as this would indent to following ~50 lines.

2022-11-09 14:00 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/FixedEquivocation.v
> +  spec Hitem_equivocating; [by subst; rewrite !elem_of_app; right; left; left |].
Do you think any improvements to the `by`-clause can salvage this?

```suggestion
    by subst; rewrite !elem_of_app, elem_of_cons; auto.
```
Or should I just rever to the previous version?

2022-11-09 14:27 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/FixedEquivocationSimulation.v
> +    destruct iom as [im |]; [| by exists [], eqv_state_s; split; [constructor |]; eauto].
```suggestion
    destruct iom as [im |]; [| by exists [], eqv_state_s; split; constructor].
```

Any better?

2022-11-09 14:46 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +    by firstorder.
`itauto` doesn't work here, probably because it can't do this `red` step that was there in the original proof that `firstorder` can handle somehow.

2022-11-09 14:49 UTC, wkolowski commented on theories/VLSM/Lib/StreamExtras.v
> +  by firstorder.
`itauto` doesn't work here. I even tried to use `itauto` after every step of the manual proof and it still doesn't work. I think `itauto` can't do first-order reasoning.

2022-11-09 14:56 UTC, wkolowski commented
@palmskog I tried to address your suggestions. I changed some of the nested stuff to be less nested. Please tell me whether the changes are good enough or whether I should revert.

I also think we should deal with `by firstorder` in a separate PR, as there are many more occurrences of it besides this PR. Tell me whether this is ok or whether I should revert.

2022-11-14 13:51 UTC, palmskog approved these changes
There are several refactorings I'm not very fond of here (subgoals being replaced with one-liners with many changed tactics). But there seems to be reasonable improvement.

2022-11-14 13:51 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/FixedEquivocationSimulation.v
> +    + destruct HcX as [Hsent | Hemitted]; [| done].
I don't really understand what is going on here, there is a single `+` goal? Please take a look.

2022-11-14 20:08 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/FixedEquivocationSimulation.v
> +    + destruct HcX as [Hsent | Hemitted]; [| done].
Good catch, indeed there was a superfluous `+`.

2022-11-14 20:51 UTC, merged