Wrap lines longer than ~100 characters
runtimeverification/vlsm pull request #133
Opened 2022-10-28 20:09 UTC by wkolowski

The coding conventions say lines should be at most 80 characters. It would be nice to follow this, but it's too much work, so I decided to wrap only these lines that don't fit into my CoqIDE window, which is around 100 characters long.

2022-10-31 12:40 UTC, palmskog reviewed
This mostly looks reasonable, but see comments about `From VLSM.X.Y`.

2022-10-31 12:40 UTC, palmskog commented on theories/VLSM/Core/ByzantineTraces/LimitedByzantineTraces.v
> +From VLSM.Core.Equivocation Require Import MsgDepLimitedEquivocation TraceWiseEquivocation.
The reason why we write `From VLSM.X` and `From VLSM.X.Y` is so we can use tools to modify/minimize the Requires and Imports. I don't think this should be changed here - instead we can have more lines with `From ...`.

2022-10-31 12:40 UTC, palmskog commented on theories/VLSM/Core/ByzantineTraces/LimitedByzantineTraces.v
> +        finite_trace_sub_projection IM selection_complement btr.
I think this is much more difficult to read than the previous sentences. Why do we need standalone lines for all connectives?

2022-10-31 12:40 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/LimitedEquivocationSimulation.v
> +From VLSM.Core.Equivocation Require Import
See other comment, I think we should use additional lines here rather than changing to `From VLSM.X.Y`.

2022-11-02 08:00 UTC, palmskog reviewed
If this was actually about doing the minimal changes to wrap lines, I'd have no problem approving it. But this is basically a code reformatting PR with a line wrapping title (see comments). I advocate doing the minimal line wrapping here and splitting out code formatting to another PR.

2022-11-02 08:15 UTC, palmskog requested changes
@wkolowski in the same vein as #132, please restrict this PR to only fixing line wrapping in the most straightforward way, and put the remaining code formatting changes in another PR.

2022-11-03 18:47 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/FixedEquivocation.v
> +                      (equivocators_state_project IM initial_descriptors is) trX ).
The idea is to indent the second line two spaces more than the expression to which it is argument, ie. `finite_valid_trace ...`. But probably it makes more sense to indent just two spaces from the `assert`.

2022-11-09 11:23 UTC, palmskog approved these changes
OK, this now looks reasonable (i.e.,I think the title is now accurate, and the content provides a benefit).

2022-11-10 15:52 UTC, merged