Playing with streams and non-empty lists
runtimeverification/vlsm pull request #138
Opened 2022-11-11 16:38 UTC by traiansf

Added non-empty lists and made some preparatory steps towards a version of stream_filtering using non-empty lists. These are intended to support a new version of VLSM projections which would stand between partial_projections and total_projection and would allow a trace item to transform into a list of trace items.

2022-11-18 12:30 UTC, palmskog approved these changes
Looks reasonable, but please consider the comments.

2022-11-18 12:30 UTC, palmskog commented on theories/VLSM/Lib/NeList.v
> +Global Infix ":::" := ne_cons (at level 60, right associativity).
```suggestion
#[export] Infix ":::" := ne_cons (at level 60, right associativity).
```
I think the usual convention is to export notations like this, not add them for everyone that recursively touches a module.

2022-11-18 12:30 UTC, palmskog commented on theories/VLSM/Lib/Preamble.v
> +      bound.
For readability, how about writing this with a proper `let` instead? `let fix helper ... in helper bound`

2022-11-18 12:35 UTC, traiansf commented on theories/VLSM/Core/VLSMProjections/VLSMStutteringEmbedding.v
> +    concatenating the translations of transition of a valid trace are valid.
Thanks! this probably means that some other similar lists should be refactored (as I copied this from elsewhere).

2022-11-18 12:42 UTC, traiansf commented on theories/VLSM/Lib/NeList.v
> +Inductive Nel (A : Type) : Type :=
Hm... I already have a `NeList` so I fear naming this `NEList` would make it confusing.
Since I don't plan to use this much (I just added it because Wojciech mentioned it), I see two options:
- giving it a longer name, like: `NonEmptyList`
- removing it altogether.

Sugegstions?

2022-11-18 12:47 UTC, palmskog commented on theories/VLSM/Lib/NeList.v
> +Inductive Nel (A : Type) : Type :=
I vote for a longer name like `NonEmptyList`.

2022-11-18 13:19 UTC, palmskog commented on theories/VLSM/Lib/NeList.v
> +Inductive NonEmptyList (A : Type) : Type :=
One more comment, this is one of those types that without closer scrutiny could turn out to be empty. Maybe you want to prove that it's inhabited?

2022-11-21 14:32 UTC, wkolowski requested changes
This is a review of everything besides `theories/VLSM/Core/VLSMProjections/VLSMStutteringEmbedding.v`.

I opened a PR with suggested changes. The changes I request are described in some of my comments.

2022-11-21 14:32 UTC, wkolowski commented on theories/VLSM/Lib/NeList.v
> +Inductive NonEmptyList (A : Type) : Type :=
I disagree. It's quite obvious that it's inhabited, given that you can use `None` to fill the second argument of `nel_cons`.

2022-11-21 14:32 UTC, wkolowski commented on theories/VLSM/Lib/NeList.v
> +    unfold proj1_sig, dexist.
```suggestion
    simpl.
```

2022-11-21 14:32 UTC, wkolowski commented on theories/VLSM/Lib/NeList.v
> +  (* for some strange reason lia doesn't work directly, so... this hack: *)
The reason is not strange. The problem is that `lia` doesn't know that `length (ne_list_to_list a)` is `>= 1`.

You should use a lemma here instead of an `assert`. Maybe an "unroll" lemma that relates `length` and `ne_list_length`?

2022-11-21 14:32 UTC, wkolowski commented on theories/VLSM/Lib/NeList.v
> +  match l with (nel_cons _ l') => l' end.
Maybe you should define `NonEmptyList` as a record instead? I think the way you did it doesn't give you the induction principle anyway.

2022-11-21 14:45 UTC, wkolowski commented on theories/VLSM/Lib/StreamExtras.v
> +    Cons (ne_list_hd l) (from_option prepend s (ne_list_tl l))) nel.
I did check a bit and I still don't understand why using `CoFixpoint` here would make the following definition of `stream_concat` non-productive. @palmskog Any ideas?

2022-11-21 14:59 UTC, wkolowski commented on theories/VLSM/Lib/NeList.v
> +Definition ne_list_foldr {A B} (f : A -> B -> B) (b : B) (l : ne_list A) :=
I forgot to mention this, but why aren't you using `Fixpoint` here?

2022-11-21 14:59 UTC, wkolowski commented on theories/VLSM/Lib/NeList.v
> +Definition ne_list_foldl {A B} (b : B) (f : B -> A -> B) (l : ne_list A) :=
As above, why `Definition` with `fix` instead of `Fixpoint`?

2022-11-21 15:00 UTC, palmskog commented on theories/VLSM/Lib/Preamble.v
> +        end
`let fix` is a standard technique see for example: https://github.com/coq-community/fourcolor/blob/master/theories/redpart.v#L1270-L1273

2022-11-21 18:57 UTC, traiansf commented on theories/VLSM/Lib/NeList.v
> +Definition ne_list_foldr {A B} (f : A -> B -> B) (b : B) (l : ne_list A) :=
People (see, e.g., stdpp) seem to like delegating things to a `fix` construct having only the iterating parameter as an argument. I don't have a clear preference towards any of the approaches.

2022-11-22 13:03 UTC, traiansf commented on theories/VLSM/Lib/Preamble.v
> +Definition compute_minimal_among_le
I've named it `find_least_among`.  The `among` is kept to keep some resemblance with `minimal_among`

2022-11-22 13:10 UTC, traiansf commented on theories/VLSM/Lib/StreamExtras.v
> +  - by cbn in *; rewrite IHl; [| cbv in *; lia].
I usually don't use `cbv`. But it seems that sometimes `lia` needs something stronger than `cbn`.

2022-11-22 14:20 UTC, traiansf commented on theories/VLSM/Lib/NeList.v
> +| ne_cons : A -> ne_list A -> ne_list A.
My habit so far was to prefix constructors (and field names) with an acronym of the type, to make them unique. I guess the acronym here would have better been `nel_` instead of `ne_`. I'll do that, and also change `ne_one` to `nel_singl`.

2022-11-22 14:40 UTC, traiansf commented on theories/VLSM/Lib/NeList.v
> +  (* for some strange reason lia doesn't work directly, so... this hack: *)
Well, it start being stranger to me if instead of the code there I write:
  `specialize (ne_list_min_length a); unfold ne_list_length; lia.`
Which I would expect to finish the proof; instead lia complains about not being able to find a witness.

2022-11-22 14:51 UTC, traiansf commented on theories/VLSM/Lib/NeList.v
> +Proof. done. Qed.
maybe I don't, but currently it helps make the two proofs I used it in smoother (using sequence of rewrites).

2022-11-22 14:57 UTC, traiansf commented on theories/VLSM/Lib/NeList.v
> +Definition ne_list_foldl {A B} (b : B) (f : B -> A -> B) (l : ne_list A) :=
I removed them both; I was playing to see how/whether it works.

2022-11-23 11:16 UTC, wkolowski commented on theories/VLSM/Lib/NeList.v
>    by apply Hle; [apply ne_list_min_length |].
I still don't like it. You should prove a lemma like `ne_list_length l = length (ne_list_to_list l)` and use it here.

2022-11-23 11:17 UTC, wkolowski commented on theories/VLSM/Lib/NeList.v
> +  match (nel_tl l) with
Parentheses around `nel_tl l` not needed.

2022-11-23 11:22 UTC, wkolowski commented on theories/VLSM/Lib/Preamble.v
> +  cbn in *.
This does nothing.

2022-11-23 12:29 UTC, wkolowski approved these changes
Looks good. I committed some suggestions.

Please address the remaining suggestions before merging.

2022-11-23 12:29 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections/VLSMStutteringEmbedding.v
> +    by eapply valid_trace_forget_last, finite_valid_trace_from_to_app_split, Htr.
```suggestion
  - subst s; apply pre_VLSM_stuttering_embedding_finite_trace_last.
    + by apply basic_VLSM_stuttering_embedding_type.
    + by eapply valid_trace_forget_last, finite_valid_trace_from_to_app_split, Htr.
```

2022-11-23 12:29 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections/VLSMStutteringEmbedding.v
> +(* end hide *)
There's `end hide`, but no `begin hide`.

2022-11-24 08:05 UTC, traiansf commented on theories/VLSM/Core/VLSMProjections/VLSMStutteringEmbedding.v
> +  (Hsimul : VLSM_stuttering_embedding X Y state_project transition_item_project).
Well, I need the preceding 4 lemmas to depend on a `VLSM_stuttering_embedding`, so they carry it as an additional argument, hence it seemed not so nice to add it to the context.  Maybe I should add a section there (and a comment) to make things more clear.

2022-11-24 08:39 UTC, merged