Remove a superfluous assumption from the lemma `nodup_append`
runtimeverification/vlsm pull request #145
Opened 2022-11-25 18:21 UTC by wkolowski

2022-11-30 13:24 UTC, bmmoore approved these changes
Looks good, if you resolve the TODO comment.

2022-11-30 14:18 UTC, palmskog requested changes
This is is fine except for removal of `set_diff_nodup'`. Please roll that back and I'll approve.

2022-11-30 14:18 UTC, palmskog commented on theories/VLSM/Lib/ListSetExtras.v
> -
@wkolowski you can see [here](https://github.com/coq/coq/blob/0f1327e33a63f6d6acb375036a3bc83c0f2262f5/theories/Lists/ListSet.v#L457-L462) that the version in Coq's stdlib is still buggy - it has the unnecessary `NoDup l'` premise. We would like to keep this correct version in our library until the issue is fixed in Stdlib. So please roll back this change.

2022-11-30 16:29 UTC, wkolowski commented on theories/VLSM/Lib/ListSetExtras.v
> -
@palmskog I got confused because there already is a lemma `set_diff_nodup` with the type we want, but it comes from `VLSM.Lib.StdppListSet`, not from the standard library. And it can be used to prove the lemma I removed simply as `by apply set_diff_nodup`, so it seems `set_diff_nodup'` is not needed after all.

I am still confused... please take a look at the most recent commit.

2022-12-01 09:56 UTC, palmskog commented on theories/VLSM/Lib/ListSetExtras.v
> -
@wkolowski here's how it was supposed to work: 
- the `StdppListSet.v` implements exactly the interface of Coq's Stdlib ListSet interface. This includes using precisely the lemma statements that are in Coq's stdlib
- the `set_diff_nodup'` was supposed to be *our* local implementation of `set_diff_nodup` with improvements applied, with an eye towards changing the version in Coq's stdlib.

However, in a PR with no stated relation to list sets, `set_diff_nodup` in `StdppListSet.v` was apparently changed in 6ec5e49267be2. I think we should roll back this change so that `StdppListSet.v`  faithfully reflects the Stdlib ListSet. However, there's no need to do this in this PR.

2022-12-01 09:57 UTC, palmskog approved these changes
This is fine by me now.

2022-12-01 12:24 UTC, wkolowski commented on theories/VLSM/Lib/ListSetExtras.v
> -
I'm still a bit confused, as the changes you linked are just to the proof of `set_diff_nodup`, but its statement had only one `NoDup` premise at that point already.

2022-12-01 12:26 UTC, merged