Add group by option to make axioms
runtimeverification/vlsm pull request #191
Opened 2023-03-20 12:52 UTC by TeodorescuIoan

The options can be activated by passing GROUPBYMOD=true to the make axioms command, for example:
```bash
make GROUPBYMOD=true axioms
```

2023-03-20 19:19 UTC, wkolowski requested changes
I think you shouldn't change the existing argument order - the new one should come at the end.

Also, can `make` parse arguments by name, instead of positionally? If so, the script should be updated to indicate that.

I also see that you have a huge duplicated chunk of code in both of the `if` branches - this should be abstracted into a function or at least factored out to the front of the `if` somehow.

2023-03-21 13:50 UTC, palmskog reviewed
I agree with @wkolowski to put the new option last. Also, recall that in Makefiles you can do stuff like `MY_VAR =? "default"` to always give a value to something, regardless of whether the user provides the option. I think this should be used here.

2023-03-28 08:47 UTC, palmskog commented
@wkolowski can you please re-review this? The argument order and other things now look good to me.

2023-03-28 13:19 UTC, wkolowski approved these changes
I tested it and it works fine, but please address my suggestions before merging (and make sure it still works after you do all the renames).

2023-03-28 13:19 UTC, wkolowski commented on scripts/axiom-diagnostics.sh
> +   GROUPBYFLAG=$4
Please use only 2 spaces on indentation to stay consistent with the rest of the file. Also, why is the variable name different here than in the makefile?

```suggestion
  group_by_mod=$4
```

2023-03-28 13:19 UTC, wkolowski commented on scripts/axiom-diagnostics.sh
> +if [ "$GROUPBYFLAG" = "true" ]; then sed -E -e 's/\t/|/' -e '/^\|/!s/()\..*$//' | awk 'BEGIN {lastModule=""} {if ($0 ~ /^\|/) { data[lastModule][$0] = 1 } else { lastModule=$0 }} END {for (key in dat
```suggestion
if [ "$group_by_mod" = "true" ]; then sed -E -e 's/\t/|/' -e '/^\|/!s/()\..*$//' | awk 'BEGIN {lastModule=""} {if ($0 ~ /^\|/) { data[lastModule][$0] = 1 } else { lastModule=$0 }} END {for (key in data) { print key; for (axiom in data[key]){ print "\t"axiom; } print "\n"; }}' | sed -E 's/\|//'; else tail -n +1; fi
```

2023-04-03 06:47 UTC, merged