Make arguments of `state` and `label` explicit
runtimeverification/vlsm pull request #216
Opened 2023-04-21 13:57 UTC by wkolowski

2023-04-21 20:30 UTC, bmmoore requested changes
I think we need to be sure that the `_` can be filled in nicely before merging this.  (The code changes look fine in themselves).

If you could use a `VLSM` name as in `state X` for some VLSM `X` I would be happy (but we should also eliminate `vstate` in favor of `state` then), but at the moment  I think the argument must be a `VLSMType` expression as in `state (vtype X)`.

This can probably be allowed by making `vtype` a Coercion.

For the next step of filling in the `_`, I think it should be acceptable to sometimes leave the `_`, if it's not very illuminating. And, this AWK script might suggest reasonable names:
```awk
BEGIN { last_var="_" }
/[[({][^ ]+ : VLSM / { match($0,"[([{]([^ ]+) : VLSM ",parts); last_var=parts[1]; }
// { gsub(/\<state _\>/,"state " last_var); print}
```

2023-04-21 20:30 UTC, bmmoore commented on theories/VLSM/Core/VLSM.v
> +Definition vlabel := label type.
Now that `state` and `label` take an explicit VLSM argument I think `vstate` and `vlabel` should be remove.
As a preliminary test, you could see where changing them to `Notation`s breaks code that tries to do some unfolding or reduction on `vstate` and `vlabel`.

2023-04-24 14:19 UTC, wkolowski commented
@bmmoore I filled in the `_` (except a few which I though were not very helpful).

I will leave adding the coercion for a separate PR, as it poses some problems (it makes a few things break). The same for `vstate` - I tried doing it right away, but it should be done in a separate step.

2023-04-25 14:06 UTC, wkolowski commented
@bmmoore I changed `state (type ...)` and `label (type ...)` to use `vstate` and `vlabel` instead, so that the style is consistent across the codebase after this PR is merged. I will remove `vstate` and `vlabel` in the next PR.

2023-04-25 16:25 UTC, bmmoore approved these changes
This is fine as an intermediate step, if you're still planning to eliminate `vstate` and `vlabel` in further work.

2023-04-25 16:45 UTC, wkolowski reviewed
Pre-commit self-review.

2023-04-25 16:46 UTC, merged