New coding convention: use lemma/theorem and tactics when proving propositions
runtimeverification/vlsm pull request #240
Opened 2023-06-08 13:11 UTC by wkolowski

…ons. Use lemma/tactics instead.

2023-06-08 16:22 UTC, palmskog commented on CODING_CONVENTIONS.md
> +- do not use definitions to prove propositions; use lemma/theorem and tactics instead
I think this is quite far in precision and accuracy from what @bmmoore and I discussed elsewhere. Specifically:
- we don't really talk about "propositions", but about terms that live in the sort `Prop` (which have Coq's weak form of proof irrelevance)
- we don't necessarily want people to use tactics beyond a single call to `exact`, and this is only to get the constants to become opaque

So, for example, one would write the "recommended" version as:
```coq
Proof. exact (map_option_app _). Qed.
```

2023-06-09 11:57 UTC, wkolowski commented on CODING_CONVENTIONS.md
> +- do not use definitions to prove propositions; use lemma/theorem and tactics instead
By "proposition" I meant a thing living in `Prop`, I can reword it if you want.

I don't understand your second point. We don't want people to use `exact`, do we? We don't use it when a subgoal can be proved by giving a term, so why should we if the entire lemma can be proved by giving a term? Also, what's the point of writing the term explicitly if we don't want to rely on the exact term and make it opaque?

2023-06-09 12:04 UTC, palmskog commented on CODING_CONVENTIONS.md
> +- do not use definitions to prove propositions; use lemma/theorem and tactics instead
The point is that writing explicit terms is the most stable and reliable way to write Coq constants. `exact` is precisely the right tactic to do this. Using tactics besides `exact` when they aren't needed leads to much harder-to-maintain code. Our goal here is to enable having opaque constant bodies even when using `Lemma`, and `Proof. exact <term>. Qed.` is the best way to accomplish this. I will request changes to any PR that changes the body of an existing `Definition` living in `Prop` to anything more loose than `exact`.

2023-06-13 17:36 UTC, bmmoore reviewed
I also think the policy description should be clarified a bit, as @palmskog says.

The code changes look fine.

I don't mind the keyword changes in this PR, but it should be clear that it's not strictly against this policy to have a `Definition ... . Proof. by (exact ...). Qed.`

2023-06-13 17:36 UTC, bmmoore commented on CODING_CONVENTIONS.md
> +- do not use definitions to prove propositions; use lemma/theorem and tactics instead
```suggestion
- To give a proof term for something in `Prop`, prefer a `Proof` with `explicit` over a `Definition` body (with `:=`). because it can be unclear whether the goal was just to give an explicit proof term, or if transparency was also intentional. To give an explicit term instead use a `Proof` with `exact` use because it is not clear whether transparency is intended or a side effect
```

2023-06-14 09:38 UTC, palmskog requested changes
This PR does too many things at once:

1. It introduces and describes new coding conventions that need to be carefully formulated and agreed on.
2. It changes a lot of existing terms to use tactic-based proofs.
3. It changes opacity (`Defined`/`Qed`) of many constants.

I think all these three items should be split into different PRs and agreed on separately. To me, the question of opacity is nearly orthogonal to using `Definition` or `Lemma`. A rule of thumb is that one should have good reasons to change opacity of existing constants.

The fact that Coq has no good mechanism to separate opacity from the mode of defining a proof script (`Qed` vs. `Defined` vs. `X := y`) is for historical reasons more than anything else. We may get an attribute like `#[opacity=transparent]` in the near future.

2023-06-15 13:22 UTC, wkolowski commented
@bmmoore I think with the new wording `Definition ... Qed` is not recommended for `Prop` (we prefer `Lemma ... Qed`) but not strictly forbidden, whereas if it's something in `Type`, then the convention does not apply.

@palmskog I removed code changes from this PR and left only the update to coding conventions. I will open a separate PR with the code changes (`Definition` to `Lemma`) and then yet another one which changes `Defined` to `Qed` (as I think there is not reason for these proofs to be transparent).

2023-06-19 07:02 UTC, palmskog approved these changes
This is fine by me now, but please consider the suggested reformulations.

2023-06-19 07:02 UTC, palmskog commented on CODING_CONVENTIONS.md
> +- When giving an explicit proof term for things that live in `Prop`, avoid using `Definition` with `:=`, because it is unclear whether the point is just to give the proof term or whether transparency
```suggestion
- When explicitly defining a constant that lives in `Prop`, avoid using `Definition` with `:=`. Instead use `Lemma` (or `Theorem`, `Proposition`, etc.) and provide the constant term body using the `exact` tactic, while indicating the opacity with `Qed` or `Defined`.
```

2023-06-19 07:02 UTC, palmskog commented on CODING_CONVENTIONS.md
> +Qed.
```suggestion
Proof. exact (map_option_app _). Qed.
```

2023-06-19 18:32 UTC, wkolowski commented on CODING_CONVENTIONS.md
> +- When giving an explicit proof term for things that live in `Prop`, avoid using `Definition` with `:=`, because it is unclear whether the point is just to give the proof term or whether transparency
Changed.

2023-06-19 18:33 UTC, wkolowski commented on CODING_CONVENTIONS.md
> +Qed.
Changed.

2023-06-19 18:42 UTC, merged