Change Definition to Lemma for proofs
runtimeverification/vlsm pull request #243
Opened 2023-06-15 13:37 UTC by wkolowski

2023-06-19 07:40 UTC, palmskog requested changes
Please change the PR so it conforms to the title.

2023-06-19 07:40 UTC, palmskog commented on theories/VLSM/Core/Equivocators/MessageProperties.v
> +Definition equivocator_has_been_received : state equivocator_vlsm -> message -> Prop :=
The title of the PR is about definitions/lemmas living in `Prop`, which this constant doesn't. What's the motivation for doing these explicit type annotations? I don't think they are very helpful, and in particular, I don't think we should be going through existing code and adding them. Types of constants are already available as part of the coqdoc documentation and through `Check`.

2023-06-19 07:40 UTC, palmskog commented on theories/VLSM/Core/TraceableVLSM.v
> +Definition composite_state_size (s : composite_state IM) : nat :=
This is another unmotivated change.

2023-06-20 11:15 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/EquivocatorsCompositionProjections.v
> +Defined.
@palmskog Funny observation: at this point `H` is used for an instance of `Finite`. When the above thing was a `Definition`, using `H` for the hypothesis name was fine, but when it's a `Lemma`, Coq rejects it and says that `H` is already used. Is this kind of behaviour intended or is it a bug?

2023-06-20 11:48 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/MessageProperties.v
> +Definition equivocator_has_been_received : state equivocator_vlsm -> message -> Prop :=
It seems I forgot to filter them out when I was splitting the PR into 3 parts. They are gone now.

As for why I always try to add them when they're missing, I find the lack of explicit type annotations very confusing and I do think they should be mandatory (and we should go over all existing code and add them).

To me having explicit annotations makes reading code more efficient, because when I need the type, I can just read it. If I don't intimately know the code, running the typechecker in my head may not be a viable option (and for many modules in VLSM it still is). Of course I can use `Check`, but it takes a couple seconds (and maybe up to 15-30 if I haven't checked the file up to that point, and maybe even a few minutes if I am looking at a branch that I didn't build yet). As for coqdoc, maybe I'm missing something, but I don't see the types anywhere if they were not explicitly written: https://runtimeverification.github.io/vlsm-docs/latest/coqdoc/VLSM.Core.Equivocators.MessageProperties.html#equivocator_has_been_received. But even if coqdoc had the types, switching between the editor and the browser takes some time, and looking up doc pages corresponding to the current file also takes some time (especially that the docs are named after the `(* *` header instead of the file name).

I just can't see why anyone wouldn't want to have explicit type annotations.

2023-06-20 11:49 UTC, wkolowski commented on theories/VLSM/Core/TraceableVLSM.v
> +Definition composite_state_size (s : composite_state IM) : nat :=
Fixed.

2023-06-20 11:49 UTC, wkolowski commented
@palmskog I have removed the unrelated changes, so you can re-review.

2023-06-20 11:50 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/MessageProperties.v
> +Definition equivocator_has_been_received : state equivocator_vlsm -> message -> Prop :=
@traiansf @bmmoore What's your opinion on explicit type annotations?

2023-06-21 03:17 UTC, bmmoore approved these changes
The actual Definition body to Proof changes are fine.

Reformatting type declarations to follow current conventions along with changing the rest of the definition is good, but some changes seem inconsistent, or unnecessarily changing away from the previous style (and the style of nearby definitions in the file) in ways that are not suggested by the coding conventions, nor big improvements in readability.

2023-06-21 03:17 UTC, bmmoore commented on theories/VLSM/Core/VLSMProjections/VLSMInclusion.v
> +      VLSM_incl X Y -> VLSM_embedding X Y id id.
This layout is pretty awkward. I would keep some arguments before the `:`
(as seen on the very next lemma `VLSM_incl_is_embedding_finite_trace_project`)

```suggestion
Lemma VLSM_incl_is_embedding
  {MX MY : VLSMMachine T}
  (X := mk_vlsm MX) (Y := mk_vlsm MY) :
    VLSM_incl X Y ->
    VLSM_embedding X Y id id.
```

2023-06-21 03:17 UTC, bmmoore commented on theories/VLSM/Lib/ListExtras.v
> +  forall {A : Type} (a : A) (l : list A),
For consistency with the other definitions around here, keep the `{A}` before `:`. Also, I think we can leave out the ` : Type` on obvious type variables, even if we generally want to annotate things.
```suggestion
Lemma app_cons {A} :
  forall (a : A) (l : list A),
```

2023-06-21 08:57 UTC, palmskog approved these changes
This looks good to me now, but please take Brandon's comments into account before merging.

2023-06-21 08:57 UTC, palmskog commented on theories/VLSM/Core/Equivocation.v
> +    ~ has_been_sent s m.
I agree with @bmmoore that the old formatting was OK, but a minor issue.

2023-06-21 08:57 UTC, palmskog commented on theories/VLSM/Core/Equivocation.v
> +  forall msg : message,
In this particular case the type is obvious, so probably it should be omitted. But minor issue.

2023-06-21 08:57 UTC, palmskog commented on theories/VLSM/Core/Equivocators/EquivocatorsCompositionProjections.v
> +Defined.
I don't think it's a bug, it's just that Coq's variable naming algorithm takes into account the form of the declaration (`Lemma` or `Definition`). The best practice is to not rely on automatic names at all, but difficult in practice.

2023-06-21 11:34 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +    ~ has_been_sent s m.
I changed it back (except that I also changed `∀` to `forall`).

2023-06-21 11:45 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +  forall m : message, ~ has_been_received s m.
Changed (except `∀` is now `forall`).

2023-06-21 11:46 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +  forall msg : message,
I'll keep it for now. As for the conventions, for me there are barely any type annotations that are unnecessary. I started a conversation about this topic as a reply to one of Karl's suggestions, you might want to have a say there.

2023-06-21 11:48 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/EquivocatorsCompositionProjections.v
> +      exists initial_descriptors,
It's just inconsistency. I only add the annotations if I notice they aren't there :)

2023-06-21 12:04 UTC, wkolowski commented on theories/VLSM/Lib/ListExtras.v
> +  forall {A : Type} (a : A) (l : list A),
Changed.

2023-06-21 12:25 UTC, merged

2023-06-21 12:40 UTC, palmskog commented on theories/VLSM/Core/Equivocation.v
> +  forall msg : message,
I completely disagree with a convention saying anything to the effect of "bare any type annotations are unnecessary". There is a long tradition in Standard ML, OCaml, HOL and Coq of using type annotations to *control* the automatic type inference. Hence, in many Coq and OCaml developments, when a type annotation is seen, it's an indication that the type inference was "wrong" about something (e.g., too general type)