Yet an alternate approach to finitely supported functions
runtimeverification/vlsm pull request #293
Opened 2023-10-26 07:52 UTC by traiansf

Using a typeclass and encapsulating finitely supported functions as a single type.

2023-10-26 07:53 UTC, traiansf commented
I'm getting the following warning about a coercion:
```
Warning: fin_supp_fn_project does not respect the uniform inheritance condition. [uniform-inheritance,coercions,default]
```
I know why I get the warning; I don't know whether I should be worried about it, though.

2023-10-26 16:27 UTC, wkolowski requested changes
It's not as horrible as I thought :) In fact it's probably good enough, but I didn't compare it with the previous version to see which one I prefer.

The notation has to go, however. I think it's better to just write `FinSuppFn`.

I opened a PR with suggestions #294

2023-10-26 16:27 UTC, wkolowski commented on theories/VLSM/Lib/FinSuppFn.v
> +  destruct (fin_supp_nat_fn_inv f) as [Heq | (n & f' & Heq)].
Since you are not using this tactic in this module, why have it? These tactics are problematic, because no one (except the author) knows they exist, so workarounds will be used.

2023-10-27 06:14 UTC, traiansf commented on theories/VLSM/Lib/FinSuppFn.v
> +Inductive FinSuppNatFn : (A -fin<> 0) -> Prop :=
Well, it it were simply the function type you would need to write parentheses; maybe it's a reason that I really view the notation as standing for a function type :-D

2023-10-27 12:03 UTC, palmskog reviewed
I think #290 is the better choice. Creating a record like `FinSuppFn` is a form of bundling, and we generally try to avoid bundling since it will decrease opportunities for automation. We also get another typeclass to maintain, when we probably have too many already.

2023-10-30 14:23 UTC, palmskog commented
@wkolowski for reference, this is the PR I prefer.

2023-10-30 14:24 UTC, palmskog approved these changes
This looks good to me.

2023-10-30 16:16 UTC, wkolowski approved these changes
The name `NatFSFun` is a bit puzzling... even though I figured it's supposed to mean "natural finitely supported function", it's still a bad name for the inductive predicate.

I pushed my suggestions directly to this branch, hopefully they won't cause trouble...

2023-10-31 15:41 UTC, merged