Refactor finishers - `reflexivity`
runtimeverification/vlsm pull request #33
Opened 2022-04-15 10:51 UTC by wkolowski

2022-04-25 13:43 UTC, palmskog reviewed
@wkolowski can you explain why you're replacing a lot of simpl calls with cbn when it's not necessary? From the refman:
> The main difference between vbn and simpl is that cbn may unfold constants even when they cannot be reused in recursive calls

I really don't see why we would want to convert all existing code to cbn. I'm fine with letting people use both simpl and cbn when they want, but there has to be a reason for changing it, and it shouldn't be done in a PR labeled something else.

2022-04-25 15:18 UTC, palmskog commented
@wkolowski in my view, there is a significant difference between advising someone to use cbn in new code and changing to cbn for existing code in a PR that is focused on something else.

Among insiders, the following properties of cbn can be reasons not to use it:
- cbn unfolds aliases even when they do not lead to further reduction
- cbn is generally slower than simpl

I'm personally not prepared to approve a PR with unnecessary simpl-to-cbn, for this reason. So I think there are two choices here:
1. separate out the cbn-to-simpl changes into a separate PR
2. we let someone else like @bmmoore or @traiansf continue the review and make the decision

2022-04-25 22:05 UTC, bmmoore requested changes
There are two complaints not about `cbn`, one that unnecessarily adds `repeat` and another where I'd rather have a space in the fancy intropattern `[= <-]` than seeing `[=<-]`.

After seeing what it looks like in the diff viewer, I'm going to insist on leaving `simpl` (or `cbn`) the way it was only in single-line changes that would otherwise touch literally nothing but removing `reflexivity`, adding `by`, and optional changing some `.` to `;`.

The point is having cleaner diffs on the commit rather than any problem with the final code, so don't worry about finding any cases of that which I didn't comment on.

2022-04-27 12:43 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/Common.v
> +  by repeat (case_decide; subst).
It works without the `repeat`. I probably thought the original code was `repeat match` instead of just `match`.

2022-04-27 12:46 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/Projections.v
> +    + by destruct Htr as [trX [[=<-] ?]]; subst.
Well, I thought it wouldn't parse *without* a space, but yeah, `[= <-]` makes more sense with a space, as it's a combination of the `=` pattern that simplifies equalities and the `<-` pattern for right-to-left rewriting.

2022-04-27 12:51 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  - by rewrite !state_update_neq.
Not sure why I didn't leave it for the next PR, but let's keep it as is.

2022-04-27 14:06 UTC, bmmoore approved these changes
Looks good now

2022-04-27 14:15 UTC, merged