Refactors finishers - `assumption`
runtimeverification/vlsm pull request #34
Opened 2022-04-19 16:24 UTC by wkolowski

2022-04-27 13:34 UTC, wkolowski reviewed
I have removed a few spurious `simpl` to `cbn` changes that Brandon wouldn't like.

2022-04-29 06:50 UTC, bmmoore requested changes
Looks pretty good, only a few little problems, and some comments.

2022-04-29 06:50 UTC, bmmoore commented on theories/VLSM/Core/Equivocators/MessageProperties.v
> +      * by left; cbn in *; rewrite Ha.
This would translate more exactly as `cbn in Ha |- *`, but I suppose it can be guessed that only evaluation in `Ha` and in the goal could be relevant because the rest is just `rewrite Ha`. Also `cbn *` takes negligible time here so performance is fine.

2022-04-29 06:50 UTC, bmmoore commented on theories/VLSM/Lib/StdppListSet.v
> +  repeat split.
Rather than introducing a repeat, maybe `split;[split|].`.

2022-04-29 06:50 UTC, bmmoore commented on theories/VLSM/Lib/ListExtras.v
> +  - by lia.
`lia` is already a finisher tactic, and we're not redundantly changing it to `by lia` elsewhere.

2022-04-29 06:50 UTC, bmmoore commented on theories/VLSM/Core/Composition.v
> +    + by destruct Hm as [[im Hinit] [=->]].
Please format as `[= ->]` so the lexing is obvious.

2022-04-29 06:50 UTC, bmmoore commented on theories/VLSM/Core/Equivocators/Composition/Projections.v
> +  by rewrite equivocator_state_project_zero.
This line lost some indentation.

2022-04-29 06:50 UTC, bmmoore commented on theories/VLSM/Core/Equivocators/Composition/Projections.v
> +  destruct (decide (eqv = (projT1 (l item)))); subst; [done |].
Is there any benefit to doing subst in the second branch, instead of following the original structure and doing it only in the first with `; [subst; done|].`?

2022-04-29 12:20 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Common.v
> +Proof. by red. Qed.
Manual says that `red` βιζ-reduces the head constant, but in practice it's mostly used for unfolding the head constant's definition.

I agree that maybe it's better to avoid it, so I'll change this to `by intro.`.

2022-04-29 12:22 UTC, wkolowski commented on theories/VLSM/Lib/StdppListSet.v
> +  repeat split.
I will change this to `split; [split |]`, but in other places I mostly tended to perform changes in the other direction. @palmskog Opinion?

2022-04-29 12:26 UTC, wkolowski commented on theories/VLSM/Lib/ListExtras.v
> +  - by lia.
Well, `lia` is good with arithmetic goals, but it doesn't subsume `assumption` and can't even prove `x = x` when `x` is not a `nat`/`Z`, so `by lia` is an improvement in many places.

But yeah, in this particular places `by lia` doesn't make any difference, so I'll change this.

2022-04-29 12:28 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +    + by destruct Hm as [[im Hinit] [=->]].
Ok, I will add a space to all occurrences of `=->` and `=<-` in the whole repo (this is just ~5 places).

2022-04-29 13:22 UTC, bmmoore commented on theories/VLSM/Lib/ListExtras.v
> +  - by lia.
No, I mean I thought lia had the property of either succeeding completely or failing that makes it a finisher on it's own, so `lia` is already does exactly the same thing as `lia; done` or `by lia` or `lia; anything`.

2022-04-29 13:27 UTC, bmmoore commented on theories/VLSM/Core/Equivocators/Composition/Projections.v
> +  destruct (decide (eqv = (projT1 (l item)))); subst; [done |].
I suggest this precisely to keep that signal clear, by only using `; subst` when the previous tactic generated equalities. Here there is only an equality in the positive case of the destruct, and not using `subst` on the side avoids the reader wondering where equalities could be coming from in the negative case.

I certainly agree we shouldn't usually leave equalities floating around for "later" (exceptions include using lemmas that need equalities as arguments), but that doesn't apply here. `;[subst |]` is still immediately adjacent in the control flow.

2022-04-29 13:59 UTC, bmmoore commented on theories/VLSM/Lib/StdppListSet.v
> +  repeat split.
The problem with `split` in particular is that `split` applies to any single-constructor types, so `repeat split` often goes past splitting on visible logical operators to also applying `constructor` to some types the reader probably hasn't memorized. It's not repetition I'm against, but unpredictability.

2022-04-29 14:09 UTC, bmmoore commented on theories/VLSM/Lib/ListExtras.v
> +  - by lia.
The stuff about what `lia` doesn't handle is why `by try lia` can be necessary.
BTW, my syntax highlighting (emacs with Proof General) has a different color for finisher tactics (at least a predefined list of them) so I had a reminder.

2022-04-29 14:12 UTC, bmmoore commented on theories/VLSM/Core/Equivocators/Composition/Projections.v
> +  by rewrite equivocator_state_project_zero.
```suggestion
    - by subst; rewrite equivocator_descriptors_update_eq.
    - rewrite equivocator_descriptors_update_neq by done; cbn.
      by rewrite equivocator_state_project_zero.
```

2022-04-29 14:26 UTC, bmmoore approved these changes
Looks good now.

Note I committed my own suggested change to put back indentation on that one line. I didn't want to leave it hanging over the weekend.

2022-04-29 14:30 UTC, wkolowski commented on theories/VLSM/Lib/StdppListSet.v
> +  repeat split.
I agree that this feature of `repeat split` should be avoided and I only use `repeat split` when it splits just the visible connectives.

2022-04-29 14:39 UTC, merged