weak full projections from component to free composition
runtimeverification/vlsm pull request #43
Opened 2022-05-24 09:43 UTC by traiansf

I realized we didn't have these generic results (we only had something similat for lifting from sub-compositions).

Once these are merged, the can be used directly for UMO and RUMO.

2022-05-24 12:30 UTC, wkolowski requested changes
Looks good, I will commit some tiny improvements. Please address the comment about `'` before I accept.

2022-05-24 12:30 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +    Definition lift_to_composite_trace'
Why the `'` in the name? There doesn't seem to be anything named `lift_to_composite_trace` neither in `caper-cbc-proofs` nor in `vlsm`.

2022-05-24 12:30 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
>        - by rewrite state_update_eq.
I have realized that this is quite a common way of reasoning across the codebase: compare two indices and then `rewrite` either `state_update_eq` or `state_update_neq` depending on the result of the comparison.

Maybe this should be automated a bit?

2022-05-24 12:30 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +        destruct Hv as [Hv _]; cbn in Hv.
```suggestion
      - destruct Ht as [[Hps [Hom [Hv _]]] Ht]; cbn in Ht, Hv.
```

You can make it a bit more compact.

2022-05-24 12:30 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +    Qed.
```suggestion
    Proof. by intros; cbn; rewrite state_update_eq. Qed.
```

No need for `unfold` here. And without `unfold`, you can fir this into one line.

2022-05-24 12:30 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +    Proof.  by intros i m Hm; exists i, (exist _ _ Hm).  Qed.
```suggestion
    Proof. by intros i m Hm; exists i, (exist _ _ Hm). Qed.
```

Some whitespace crept in.

2022-05-24 12:30 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +      - by intros * ? * [_ Ht]; apply lift_to_composite_transition_preservation.
```suggestion
      - by inversion 1; apply lift_to_composite_transition_preservation.
```

I don't like this elaborate pattern. I think it would be better to more explicitly state that you just want to invert the first non-dependent hypothesis.

2022-05-24 12:30 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +        + by eapply lift_to_composite_initial_message_preservation.
```suggestion
        by eapply lift_to_composite_initial_message_preservation.
```

No need for the bullet.

2022-05-24 12:30 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +      constructor; intros.
@palmskog What was the consensus on naming hypotheses? Should we do it only if the names are actually used in the proof?

2022-05-25 06:22 UTC, traiansf commented on theories/VLSM/Core/Composition.v
> +    Definition lift_to_composite_trace'
I was trying to make it consistent with the name for the state. But given that that name was not much better, I decided to change it.

2022-05-25 09:33 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
>        - by rewrite state_update_eq.
@traiansf I have already started to feel the need for that myself, when juggling some lemmas in the UMO PR. Maybe I will open a PR with such a tactic (and some refactorings) sometime in the future.

2022-05-25 10:02 UTC, wkolowski requested changes
I still don't like the naming. We need to strike a balance between being descriptive and short.

Another suggestion: maybe the versions that lift to initial composite state should just get a `'` appended to the end of the name for the general version?

And why aren't the initial versions defined in terms of the general versions? Is it just to avoid lengthy `unfold`ing chains?

2022-05-25 11:36 UTC, wkolowski approved these changes

2022-05-25 11:40 UTC, merged