Equivocation definitions based on Message Dependencies
runtimeverification/vlsm pull request #57
Opened 2022-06-24 12:44 UTC by traiansf

2022-06-24 14:50 UTC, wkolowski requested changes
I think you should try to refactor the `Unshelve` and also refactor `Comparable` before this PR can be merged. Besides, I think there are quite a few typos. I will commit my proof-engineering-related suggestions.

2022-06-24 14:50 UTC, wkolowski commented on theories/VLSM/Lib/Preamble.v
> +| comparable_ba : forall a b, R b a -> Comparable R a b.
This looks very suspicious.

In the standard library, there is a type `comparison`, defined as

```coq
Inductive comparison : Set :=  Eq : comparison | Lt : comparison | Gt : comparison.
```

Then, there is a predicate `CompareSpec` defined as

```coq
Inductive CompareSpec (Peq Plt Pgt : Prop) : comparison -> Prop :=
  | CompEq : Peq -> CompareSpec Peq Plt Pgt Eq
  | CompLt : Plt -> CompareSpec Peq Plt Pgt Lt
  | CompGt : Pgt -> CompareSpec Peq Plt Pgt Gt.
```

(There's also `CompareSpecT`, which is a `Type` instead of a `Prop`.)

These two together probably are better than your `Comparable`, as you can use `comparison` to define ordinary, non-dependent functions, and then you can use `CompareSpec` to assign meaning to the results of these functions.

Your `Comparable` is like a blend of `comparison` and `CompareSpec` that only applies to `relation`s.

I think you should try to refactor this using `comparison` and `CompareSpec`.

2022-06-24 14:50 UTC, wkolowski commented on theories/VLSM/Lib/Preamble.v
> +  - by constructor 3.
```suggestion
  by intros [|[|]]; constructor.
```

2022-06-24 14:50 UTC, wkolowski commented on theories/VLSM/Lib/Preamble.v
> +  - by constructor 3; constructor.
```suggestion
  by intros *; inversion 1; repeat constructor.
```

2022-06-24 14:57 UTC, traiansf commented on theories/VLSM/Lib/Preamble.v
> +| comparable_ba : forall a b, R b a -> Comparable R a b.
You are probably right, but then we should probably get rid of the `comparable` definition next to this.

2022-06-27 06:08 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +  done.
Hm.. apparently I just needed to move the cbn a little earlier. Without it, it was harder for Coq to figure out the precise instance I was referring to.

2022-06-27 07:50 UTC, palmskog commented on theories/VLSM/Lib/Preamble.v
> +| comparable_ba : forall a b, R b a -> Comparable R a b.
I agree with @wkolowski that it would be desirable to purge `comparable`/`Comparable` in favor of `comparison` from Stdlib, preferably everywhere. @traiansf could we switch to `comparison`/`CompareSpec` just in this PR and ignore the other stuff from before for now?

2022-06-27 13:08 UTC, wkolowski approved these changes
Looks good.

2022-06-27 17:22 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +  (** 'composite_has_been_directly_observed' is decidable. *)
I think you want `[]` here instead of single quotes.

2022-06-28 12:25 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +Lemma proper_not_directly_observed `(vlsm : VLSM message) `{HasBeenDirectlyObservedCapability message vlsm}:
It might, but I don't think it's relevant here. The point of the `proper_not_directly_observed` result is to say that if a message is not directly observed, then it won't appear as sent or receive on any valid trace leading to s

2022-06-28 12:29 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +  [has_been_directly_observed] for any of its components.
To compromise, I'll change 'for' to 'in'
'by' would imply that the state is the observer, which doesn't feel adequate to me.

2022-06-28 12:39 UTC, traiansf commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +      apply composite_has_been_directly_observed_sent_received_iff.
The definition composite_has_been_directly_observed s m is given as exists i, has_been_directly_observed (s i) m
This lemma says the definition is equivavalent to the disjunction between composite_has_been_sent and composite_has_been_received

2022-06-28 13:18 UTC, merged