Full message dependencies
runtimeverification/vlsm pull request #6
Opened 2022-01-20 12:54 UTC by traiansf

Generic models for fixed-set and limited message equivocation based on message dependencies without assuming the full node condition for the validity predicate.

2022-01-26 14:34 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections.v
> +  - cbv; intuition.
```suggestion
  apply basic_VLSM_incl.
  1, 3-4: cbv; intuition.
  intros _ _ m _ _ [Him | Hp].
  - apply initial_message_is_valid. left. assumption.
  - apply PimpliesQorValid in Hp as [Hq | Hvalid]; [|assumption].
    apply initial_message_is_valid. right. assumption.
```

2022-01-26 14:34 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      assumption.
I think this is one case where a forward proof does better than a backward one :)

```suggestion
      intros item Hitem.
      apply elem_of_list_split in Hitem as (l1 & l2 & Heq).
      eexists _,_.
      eapply input_valid_transition_to; [eassumption|].
      simpl. eassumption.
```

2022-01-26 14:34 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      assumption.
No need to convert `elem_of` to `In` before splitting. There's `elem_of_list_split`.

```suggestion
      intros item Hitem.
      apply elem_of_list_split in Hitem as (pre & suf & Heqtr).
      exists suf.
      replace (destination item)
         with (finite_trace_last is (pre ++ [item]))
           by apply finite_trace_last_is_last.
      eapply finite_valid_trace_from_to_app_split.
      rewrite <- app_assoc. simpl. rewrite <- Heqtr.
      assumption.
```

2022-01-26 14:34 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      eassumption.
Again.

```suggestion
      intros item Hitem.
      apply elem_of_list_split in Hitem as (pre & suf & Heqtr).
      exists (pre ++ [item]).
      replace (destination item)
         with (finite_trace_last is (pre ++ [item]))
           by apply finite_trace_last_is_last.
      eapply finite_valid_trace_from_to_app_split.
      rewrite <- app_assoc. simpl. rewrite <- Heqtr.
      eassumption.
```

2022-01-26 14:34 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +Qed.
I would try to avoid `Program` as much as possible.

```suggestion
Program Definition sub_index_list_annotate : list sub_index :=
  list_annotate sub_index_prop sub_index_list ltac:(apply Forall_forall; intuition).
```

2022-01-26 14:34 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +    apply elem_of_list_annotate.
```suggestion
  - intro sub_x.
    apply elem_of_remove_dups, elem_of_list_annotate.
```

2022-01-26 14:34 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +Unshelve.
Again, I would try to avoid `Unshelve`.

2022-01-26 14:34 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  intuition.
```suggestion
  intros m Hm.
  eapply VLSM_incl_can_emit.
  - apply pre_loaded_vlsm_incl_relaxed with (P0 := fun m => Q m \/ P m).
    intuition.
  - eapply VLSM_full_projection_can_emit; [|eassumption].
    apply preloaded_sub_element_full_projection.
    intuition.
```

2022-01-28 06:52 UTC, traiansf commented on theories/VLSM/Core/MessageDependencies.v
> +Definition msg_dep_happens_before : relation message := flip (clos_trans _ (flip msg_dep_rel)).
I don't know. I'm using the equivalence between them below; however, I kind of like the naming better; everyone would understand we're talking about transitive closure when I'm using `clos_trans`; however they might start asking questions if they see `clos_trans_1n`

2022-01-28 06:56 UTC, traiansf commented on theories/VLSM/Core/SubProjectionTraces.v
> +Qed.
Frankly, I don't see why this would be better.
In my opinion, if we need to use `Program Definition`, then it's better looking to keep the obligations separate.

2022-01-28 07:05 UTC, traiansf commented on theories/VLSM/Core/MessageDependencies.v
> +  apply msg_dep_happens_before_reflect.
Apparently the `firstorder` tactic at the end of the proof of `msg_dep_happens_before_reflect` decided to use the hasbeensent and hasbeenreceived capabilities from the context. Clearing them before the induction solved this issue.

2022-01-28 07:23 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +      [message : Type]
I've seen @bmmoore  using `[ ]` and they generally seem to make usage better, but I don't have a clear opinion on them so I'll defer to the experts

2022-01-28 07:51 UTC, traiansf commented on theories/VLSM/Core/SubProjectionTraces.v
> +Unshelve.
I tried your suggestion (you can check the results), but I think in this case it might have been better to use Unshelve, as it is a pretty small proof.

2022-01-28 12:56 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +Definition msg_dep_happens_before : relation message := flip (clos_trans _ (flip msg_dep_rel)).
Well, I would use whichever definition gives the shortest proofs and tell people that `clos_trans_1n` is transitive closure defined in a particular formal-proof-friendly way. If they are reading it in Alectryon/coqdoc documentation/interactively, they can just see the definition for themselves.

Anecdotally, people like me start asking questions when they see `trans_clos`, as definitions of this kind have given them their fair amount of headache over the years.

2022-01-31 13:04 UTC, palmskog commented on theories/VLSM/Core/Equivocation.v
> +      [message : Type]
The difference between `{ }` and `[ ]` is the former is *maximally* implicitly inserted, while the latter is non-maximally implicitly inserted. 

The difference to a user is often not all that noticeable, so I think we should try to be consistent across files. That is, since, we mostly use `{ }` elsewhere. @bmmoore or do you have some other rule of thumb here?

2022-01-31 13:19 UTC, palmskog commented on theories/VLSM/Core/Equivocation.v
> +    + auto.
I personally think it's fine to use `assumption`, it's a well-understood tactic that's not likely to break without proper cause.

On the other hand, `exact Hom'` breaks if we change the not-so-great name `Hom'`, and in my view it's "too specific" to end a proof with...

2022-01-31 13:21 UTC, palmskog commented on theories/VLSM/Core/Equivocation.v
> +    pose (Xhbr := composite_HasBeenReceivedCapability has_been_received_capabilities constraint).
Using `pose` is typically fine by me, but maybe one could use `typeclasses eauto` somewhere instead or as a complement? If instance resolution is used, that is.

2022-02-01 17:28 UTC, wkolowski requested changes
Please investigate the typeclass stuff. I will review the rest later.

2022-02-01 17:28 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +  forall dm, dm ∈ message_dependencies m -> has_been_observed X s dm.
Maybe you should use `Forall` instead of a combination of `forall`, `elem_of` and `->`?

2022-02-01 17:28 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +    assumption.
```suggestion
    contradict Hinit. apply no_initial_messages_in_X.
```

2022-02-01 17:28 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +      }
As I pointed out previously, I don't like using `cut` like this. Maybe you should factor this into a lemma instead?

2022-02-01 17:28 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +    replace (Some m) with (output item) by assumption.
Using `rewrite` here would be as confusing as using `assumption`, but much shorter.

```suggestion
    rewrite <- Houtput.
```

2022-02-01 17:28 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +    apply Htr.
I don't like `apply Htr` here, because `Htr` is a conjunction and the `apply` implicit `destruct`s it. I'm not sure, however, if there's a cleanlier way to write it.

2022-02-01 17:28 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +    ; [intros [Hsent | Hreceived]; [left | right]; exists i; assumption|].
This `cut` is a bit inconsistent in style with the previous `cut`s. Also, I think I have already seen this proof `intros [Hsent | Hreceived]; [left | right]; ...`. Maybe you should really consider making this a lemma?

2022-02-01 17:28 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +    cbn.
```suggestion
    unfold composite_project_label; cbn.
```

2022-02-01 17:28 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +    ; [elim (no_initial_messages_in_IM i im); assumption|contradiction| assumption].
Again.

```suggestion
    intros [[[i [[im Him] _]] | Hpreloaded] | Hemit]; intuition.
    contradict Him. apply no_initial_messages_in_IM.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +    cbn.
I don't like this `exact` here, but sadly `trivial` doesn't work.

```suggestion
    split; [cbn |exact I].
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +    + subst.
```suggestion
  - intros l s om s' om'; cbn.
    rewrite sub_element_state_eq with (H_j := Hj).
    intro Ht; replace (vtransition _ _ _) with (s', om'); f_equal.
    extensionality sub_i.
    destruct_dec_sig sub_i i Hi Heqsub_i; subst.
    destruct (decide (i = j)); subst.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +    + subst. rewrite sub_element_state_eq. assumption.
```suggestion
    destruct_dec_sig sub_i i Hi Heqsub_i; subst.
    destruct (decide (i = j)); subst.
    + rewrite sub_element_state_eq. assumption.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  match decide (j = ` (projT1 l)) with
There's `projT1` and backtick (i.e. `proj1_sig`) on the same line, which means you desperately need more records there : )

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  cbn in HlX, HtX.
Put related atomic tactics together with `;`.

```suggestion
  destruct_dec_sig sub_i i Hi Heqsub_i; subst.
  unfold sub_label_element_project in HlX; cbn in HlX, HtX.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  clear HlX.
I think this `clear` muddles more than helps.

```suggestion
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  inversion HtX. subst. clear HtX.
```suggestion
  inversion_clear HtX.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  assumption.
```suggestion
  intros lY.
  unfold sub_element_label, sub_label_element_project; cbn.
  rewrite decide_left with (HP := eq_refl); cbn.
  reflexivity.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  assumption.
This proof and the above one look very similar, isn't there some possibility to factor something out?

```suggestion
  intros sY.
  unfold sub_element_state, sub_state_element_project; cbn.
  rewrite decide_left with (HP := eq_refl); cbn.
  reflexivity.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +    sub_state_element_project sX1' = sub_state_element_project sX2' /\ oom1 = oom2.
```suggestion
Lemma sub_transition_element_project_Some :
  forall lX1 lX2 lY,
    sub_label_element_project lX1 = Some lY ->
    sub_label_element_project lX2 = Some lY ->
  forall sX1 sX2,
    sub_state_element_project sX1 = sub_state_element_project sX2 ->
  forall iom sX1' oom1,
    composite_transition (sub_IM IM indices) lX1 (sX1, iom) = (sX1', oom1) ->
  forall sX2' oom2,
    composite_transition (sub_IM IM indices) lX2 (sX2, iom) = (sX2', oom2) ->
      sub_state_element_project sX1' = sub_state_element_project sX2' /\ oom1 = oom2.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  reflexivity.
```suggestion
  intros (sub_j1, lj1) (sub_j2, lj2) lj.
  destruct_dec_sig sub_j1 j1 Hj1 Heqsub_j1;
  destruct_dec_sig sub_j2 j2 Hj2 Heqsub_j2; subst.
  unfold sub_label_element_project; cbn.
  do 2 (case_decide; inversion 1); subst; cbn in *; subst.
  unfold sub_state_element_project.
  intros sX1 sX2 Hsjeq iom.
  replace (sX1 (dec_exist (sub_index_prop indices) j Hj1)) with (sX1 (dexist j Hj))
    by apply sub_IM_state_pi.
  replace (sX2 (dec_exist (sub_index_prop indices) j Hj2)) with (sX2 (dexist j Hj))
    by apply sub_IM_state_pi.
  rewrite <- Hsjeq.
  unfold sub_IM; cbn.
  destruct (vtransition _ _ _) as (si', om').
  do 2 inversion_clear 1.
  split; [|reflexivity].
  setoid_rewrite sub_IM_state_update_eq.
  reflexivity.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +      setoid_rewrite induced_sub_projection_transition_is_composite.
```suggestion
    + intro; apply sub_element_label_project.
    + intro; apply sub_element_state_project.
    + intro; setoid_rewrite induced_sub_projection_transition_is_composite.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      simpl. eassumption.
```suggestion
      eapply input_valid_transition_to; cbn; eassumption.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      replace (Some m) with (output item) by assumption.
```suggestion
      intros (item & Hitem & Houtput).
      exists (destination item).
      unfold can_produce.
      rewrite <- Houtput.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      rewrite <- app_assoc. simpl. rewrite <- Heqtr.
```suggestion
      erewrite <- finite_trace_last_is_last.
      eapply finite_valid_trace_from_to_app_split.
      rewrite <- app_assoc; cbn; rewrite <- Heqtr.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      rewrite <- app_assoc. simpl. rewrite <- Heqtr.
```suggestion
      erewrite <- finite_trace_last_is_last.
      eapply finite_valid_trace_from_to_app_split.
      rewrite <- app_assoc; cbn; rewrite <- Heqtr.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      ; [assumption|].
```suggestion
      apply (extend_right_finite_trace_from X); [assumption|].
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      subst. reflexivity.
```suggestion
      repeat split. 1, 3-4: assumption.
      destruct iom as [m|]; [|apply option_valid_message_None].
      apply option_valid_message_Some, Hobs.
      red. rewrite Exists_app, Exists_cons.
      subst; cbn; firstorder.
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections.v
> +    finite_trace_last_output trX = finite_trace_last_output (pre_VLSM_full_projection_finite_trace_project trX).
```suggestion
Lemma pre_VLSM_full_projection_finite_trace_last_output :
  forall trX,
    finite_trace_last_output trX
      =
    finite_trace_last_output (pre_VLSM_full_projection_finite_trace_project trX).
```

2022-02-02 03:44 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections.v
> +  reflexivity.
```suggestion
  intros trX.
  destruct_list_last trX trX' lst HtrX; [reflexivity|].
  setoid_rewrite map_app; simpl; rewrite !finite_trace_last_output_is_last.
  reflexivity.
```

2022-02-02 08:36 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +  split; auto.
I'm glad you're moving towards this conclusion :-)

2022-02-02 08:43 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +  destruct Hobserved as [Hsent | Hreceived].
I think that here it's fine, probably, since the following proof is very short; however, when a long proof follows, I usually like to have my hypotheses named properly, as they are easier to locate; also naming them does no harm and it can be considered as some sort of documentation.

2022-02-02 08:46 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +      apply composite_no_initial_valid_messages_emitted_by_sender; assumption.
I don't mind trying to avoid revert, but (1) why? and (2) sometimes using revert helps the application figure out context faster.
In general, it seems to me that `eapply` is slower and might shelve goals, so I'd like to know why do we prefer it. Maybe this is something which could be discussed in the coding conventions, too.

2022-02-02 08:50 UTC, traiansf commented on theories/VLSM/Core/MessageDependencies.v
> +  forall dm, dm ∈ message_dependencies m -> has_been_observed X s dm.
I know that it's more concise, and I tried to implement that usage pattern before, but I'm usually finding that there aren't sufficient lemmas for Forall and I (too often) need to use Forall_forall to turn it into the form above.  Nevetheless, I'll give your suggestion a try.

2022-02-02 08:53 UTC, traiansf commented on theories/VLSM/Core/MessageDependencies.v
> +    apply Htr.
But we apply lemmas whose conclusions are conjunctions all of the time (after all, `<->` is itself a conjunction). The alternative would be to destruct Htr, or to apply a projection to it first, but I'm not sure that would improve readability.

2022-02-02 13:07 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      apply composite_no_initial_valid_messages_emitted_by_sender; assumption.
@traiansf I have the feeling that, if you need to `revert` for `apply` to work, you have set up your theorem in a suboptimal way. The people who come after you and try to `apply` your theorem will find it hard to do.

2022-02-02 13:11 UTC, wkolowski commented on theories/VLSM/Core/MessageDependencies.v
> +    apply Htr.
In my mind you are not supposed to `apply` lemmas that say `P <-> Q`, but to `rewrite` them. Anyway, I don't see how to improve it in this particular case.

2022-02-02 13:16 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +  assumption.
@traiansf Any reason why you skipped this suggestion?

2022-02-02 14:24 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +      [message : Type]
I would argue that in this particular context I've used `[]` to maintain local consistency: both the lemmas above and those below are using `[]` (I think their original author was Brandon).  Nevetheless, I will change the new lemmas I added to use `{}`.

2022-02-02 14:31 UTC, traiansf commented on theories/VLSM/Core/SubProjectionTraces.v
> +  assumption.
I sometimes want to manually perform the suggestions to understand them better.

2022-02-04 18:56 UTC, traiansf commented
@wkolowski Since you've blocked my PR until resolving class inference for HasBeen stuff, I obliged, although I was thinking this is a task more suitable for proof engineering experts like yourself and Karl. Please check the results in https://github.com/runtimeverification/vlsm/pull/6/commits/99d0b726729c5c3fea672b459f2343d4c3daec26

I think there are still some suggestions you left I haven't looked at, but I'll do them while you look over this bigger change.

2022-02-04 22:47 UTC, wkolowski reviewed
So far looks pretty good. I will review the rest and approve on Monday (if I don't die from covid by then).

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +  - intros ls s om s' om' [_ Ht]. apply lift_sub_transition. assumption.
```suggestion
  - intro; intros; apply pre_loaded_fixed_non_byzantine_vlsm_lift_valid; assumption.
  - intro; intros * []; apply lift_sub_transition; assumption.
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +    exact (proj1 Hv).
```suggestion
    destruct Hv; assumption.
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
>      apply induced_sub_projection_transition_preservation.
Don't `revert` before `apply`ing if you can `apply` and then use an `assumption`.

```suggestion
    apply (VLSM_full_projection_input_valid pre_loaded_fixed_non_byzantine_vlsm_lift).
    assumption.
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
>  Proof.
Again, can't post a suggestion.

```coq
  apply induced_sub_projection_constraint_subsumption_incl.
  intros l (s, om) Hv.
  apply (fixed_strong_equivocation_subsumption IM selection)
    in Hv as Hstrong_v.
  destruct Hv as (Hs & Hom & Hv & Hc).
  destruct om; [| trivial].
  cbn; destruct (sender m) as [v |] eqn: Hsender; [| exact I]; cbn.
  case_decide as HAv; [| trivial].
  unfold sub_IM; cbn.
  apply (VLSM_incl_valid_state (constraint_free_incl IM (fixed_equivocation_constraint IM selection))) in Hs.
  apply (VLSM_incl_valid_state (vlsm_incl_pre_loaded_with_all_messages_vlsm (free_composite_vlsm IM))) in Hs.
  assert (Hpre_si : forall i, valid_state_prop (pre_loaded_with_all_messages_vlsm (IM i)) (s i)).
  {
    intro i.
    revert Hs.
    apply valid_state_project_preloaded_to_preloaded.
  }
  apply set_diff_elim2 in HAv.
  destruct Hstrong_v as [(i & Hi & Hsent) | Hemitted].
  - apply valid_state_has_trace in Hs as (is & tr & Htr).
    eapply has_been_sent_iff_by_sender; [| | | exists i]; eassumption.
  - contradict HAv. eapply sub_can_emit_sender; eassumption.
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
>  Proof.
Again, can't post a suggestion.

```coq
  apply basic_VLSM_incl.
  - intros s (sX & <- & Hinitial) sub_i.
    apply Hinitial.
  - intro; intros.
    apply (VLSM_incl_input_valid fixed_non_equivocating_incl_sub_non_equivocating)
      in Hv as (Hs & _ & Hv).
    apply sub_IM_no_equivocation_preservation in Hv as Hnoeqv.
    2-4: assumption.
    destruct Hnoeqv as [Hsent | Hseeded].
    + eapply preloaded_composite_sent_valid; eassumption.
    + apply initial_message_is_valid.
      right; split; [assumption|].
      eapply induced_sub_projection_valid_projection. apply Hv.
  - intros l s om Hv.
    apply (VLSM_incl_input_valid fixed_non_equivocating_incl_sub_non_equivocating)
       in Hv as (_ & _ & Hv).
    split.
    + revert Hv.
      apply induced_sub_projection_valid_preservation.
    + split; [| exact I].
      apply sub_IM_no_equivocation_preservation in Hv as Hnoequiv.
      2-4: assumption.
      destruct om as [m |]; [| trivial].
      destruct Hnoequiv as [Hsent|Hseeded]; [left; assumption | right].
      split; [assumption|].
      eapply induced_sub_projection_valid_projection. apply Hv.
  - intros l s om s' om' [_ Ht].
    revert Ht.
    apply induced_sub_projection_transition_preservation.
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +  - intro; intros. cbv; trivial.
As I wrote previously, I don't like `intro; intros`, but not sure how to improve on it.

```suggestion
  - intro; intros; apply lift_sub_transition; assumption.
  - intro; intros; apply (lift_sub_state_initial IM); assumption.
  - intro; intros; cbn; trivial.
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +  - intros l s om. apply Hfixed_non_byzantine_vlsm_lift_initial_message.
```suggestion
  - intro; intros; apply fixed_non_byzantine_vlsm_lift_valid; assumption.
  - intro; intros * []; apply lift_sub_transition; assumption.
  - intro; intros; apply (lift_sub_state_initial IM); assumption.
  - intros; apply Hfixed_non_byzantine_vlsm_lift_initial_message.
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +    apply (lift_sub_state_initial IM); assumption.
```coq
    split.
    + apply composite_state_sub_projection_lift_to.
    + apply (lift_sub_state_initial IM); assumption.
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +    apply proj1 in Hv.
```suggestion
    eapply Hfixed_non_byzantine_vlsm_lift_initial_message.
    1, 3: eassumption.
    destruct Hv as [Hv _].
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
>      apply induced_sub_projection_transition_preservation.
```suggestion
    apply induced_sub_projection_transition_preservation; assumption.
```

2022-02-04 22:47 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/LimitedByzantineTraces.v
>  Proof.
Nice, I didn't know about `specialize ... as`.

```coq
  apply basic_VLSM_full_projection; intros ? *.
  - intros; apply limited_PreNonByzantine_lift_valid; assumption.
  - intros * []; apply lift_sub_transition; assumption.
  - intros; apply (lift_sub_state_initial IM); assumption.
  - intros Hv HsY [[sub_i [[im Him] Heqm]] | Hseeded].
    + cbn in Heqm; subst.
      destruct_dec_sig sub_i i Hi Heqsub_i; subst.
      unfold sub_IM in Him; cbn in Him; clear -Him.
      apply initial_message_is_valid.
      exists i, (exist _ m Him). reflexivity.
    + destruct Hseeded as (Hsigned & i & Hi & li & si & Hpre_valid).
      apply set_diff_elim2 in Hi.
      specialize (Hvalidator i _ _ Hpre_valid) as (_ & _ & _ & Hmsg & _).
      assumption.
```

2022-02-07 08:16 UTC, traiansf commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
>      apply induced_sub_projection_transition_preservation.
I'm trying to understand why your proposal would be better. Could you please provide an argument for that?
In my view the revert there is helpful as it provides more context for the apply, which can then be simpler.

2022-02-07 14:07 UTC, palmskog commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
>      apply induced_sub_projection_transition_preservation.
`revert` has a bit of an unfortunate name (it sounds regressive). But in reality, moving terms between the context and the goal is done all the time in advanced projects like MathComp. However, regular Ltac don't have good facilities for streamlining this. In SSReflect, one would do:
```coq
move=> l s om s' om' [_ Ht].
apply/induced_sub_projection_transition_preservation: Ht.
```
So bottom line, I think Traian should keep this as-is.
```

2022-02-07 22:39 UTC, wkolowski reviewed
There are too many forward proofs. I will continue reviewing tomorrow.

2022-02-07 22:39 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections.v
> +    apply initial_message_is_valid. right. assumption.
```suggestion
  - apply initial_message_is_valid; left; assumption.
  - apply PimpliesQorValid in Hp as [Hq | Hvalid]; [|assumption].
    apply initial_message_is_valid; right; assumption.
```

2022-02-07 22:39 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections.v
> +    intuition.
```suggestion
  - apply pre_loaded_vlsm_incl; contradiction.
```

2022-02-07 22:39 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      eapply can_produce_from_valid_trace; [apply Htr|assumption].
```suggestion
      apply can_emit_iff.
      setoid_rewrite Exists_exists in Hm.
      destruct Hm as (item & Hitem & Houtput).
      exists (destination item).
      unfold can_produce; rewrite <- Houtput.
      eapply can_produce_from_valid_trace; [apply Htr | assumption].
```

2022-02-07 22:39 UTC, wkolowski commented on theories/VLSM/Core/VLSM.v
> +      subst; cbn; firstorder.
And another slightly forward proof. Can you try to get rid of the `apply ... in`?
```suggestion
    revert s Htr Hobs.
    induction tr using rev_ind; intros; split
    ; [|apply Htr | | apply Htr]
    ; destruct Htr as [Htr Hinit].
    - inversion Htr; subst.
      apply (finite_valid_trace_from_to_empty X).
      apply initial_state_is_valid.
      assumption.
    - apply finite_valid_trace_from_to_last in Htr as Hlst.
      apply finite_valid_trace_from_to_app_split in Htr.
      destruct Htr as [Htr Hx].
      specialize (IHtr _ (conj Htr Hinit)).
      spec IHtr.
      {
        intros. apply Hobs.
        apply trace_has_message_prefix. assumption.
      }
      destruct IHtr as [IHtr _];
      apply finite_valid_trace_from_to_forget_last in IHtr.
      apply finite_valid_trace_from_add_last; [| assumption].
      inversion Hx; subst f tl s'.
      apply (extend_right_finite_trace_from X); [assumption |].
      destruct Ht as [[_ [_ Hv]] Ht].
      apply finite_valid_trace_last_pstate in IHtr as Hplst.
      repeat split. 1, 3-4: assumption.
      destruct iom as [m |]; [| apply option_valid_message_None].
      apply option_valid_message_Some, Hobs.
      red; rewrite Exists_app, Exists_cons.
      subst; cbn; intuition.
```

2022-02-07 22:39 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/MessageProperties.v
>  Lemma equivocator_has_been_sent_stepwise_props
This proof is very similar to `equivocator_has_been_received_stepwise_props`, maybe there's a way to factor the commonality out?

2022-02-08 07:02 UTC, traiansf commented
> There are too many forward proofs. I will continue reviewing tomorrow.

While I agree that there might be a lot of forward proofs, I would say this is outside the scope of this PR and I don't think that the mere fact that a refactoring touched a proof should automatically trigger a rewrite of that proof.  If you want, I don't mind you opening a PR where you take all the proofs in the VLSM repo and rewrite then to your satisfaction.

2022-02-08 07:06 UTC, traiansf commented on theories/VLSM/Core/Equivocation/NoEquivocation.v
>        right. assumption.
I probably could, but I would prefer not to do it as part of this PR.

2022-02-08 07:09 UTC, traiansf commented on theories/VLSM/Core/Equivocation/NoEquivocation.v
>    Lemma composite_observed_were_sent_invariant s:
yes, I agree (both that this is extreme, and that you are right :-D ), but note that it's not part of the change of this PR.
Also, some would argue that in regular writing one doesn't usually put spaces before most punctuation signs :-) so I guess this is how this came to be (in fact there is another instance of that in the definition above.

2022-02-08 07:24 UTC, traiansf commented on theories/VLSM/Core/Equivocation/NoEquivocation.v
>    Lemma composite_observed_were_sent_invariant s:
I was actually planning to implement the change you suggested, but then I realized that there are a  lot more lemmas written in a similar fashion, so I decided to just add a TODO to make notation uniform across the file,

2022-02-08 07:30 UTC, palmskog commented on theories/VLSM/Core/Equivocation/NoEquivocation.v
> +    apply Hinv.
I disagree that there is some inherent superiority to backward proofs, such as that backward proofs are more maintainable. Regular mathematicians argue both forward and backward, as was highlighted in the odd-order theorem proof in Coq that followed the paper proof. They ended up using both `rewrite` and `have` in SSReflect in decent proportions.

We have pretty good evidence that extracting out *standalone lemmas* is a good thing for maintainability, though. But this requires quite a lot of extra effort, so not always worth it.

2022-02-08 22:45 UTC, wkolowski reviewed
I feel that when I'm ill, my suggestion fall in quality significantly...

2022-02-08 22:45 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      : oracle_stepwise_props selector' oracle.
I think that 2 spaces of indentation is enough here and in other places too.

```suggestion
  [message] [vlsm : VLSM message]
  [selector]
  [oracle : state_message_oracle vlsm]
  (Horacle : oracle_stepwise_props selector oracle)
  selector'
  (Heqv :
    forall s item,
      input_valid_transition_item (pre_loaded_with_all_messages_vlsm vlsm) s item ->
      forall m, selector m item <-> selector' m item)
  : oracle_stepwise_props selector' oracle.
```

2022-02-08 22:45 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +  - apply proj1 in Hall. specialize (Hall Hobs).
I think `apply proj1` is a code smell and we should prefer `destruct` instead.

```suggestion
  - destruct Hall as [Hall _]. specialize (Hall Hobs).
```

2022-02-08 22:45 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +      eapply Hreceived; eassumption.
```coq
  apply stepwise_props_from_trace
  ; [apply has_been_observed_from_sent_received_dec|..]
  ; intros; split.
  - intros [Hsent | Hreceived] start tr Htr.
    + apply proper_sent in Hsent; [|assumption].
      apply Exists_or; right.
      eapply Hsent; eassumption.
    + apply proper_received in Hreceived; [|assumption].
      apply Exists_or; left.
      eapply Hreceived; eassumption.
```

2022-02-08 22:45 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
>      destruct Hexists as [Hsent | Hreceived].
Sorry for posting suggestions to lines you didn't touch, maybe you're right and my reviewing style is too broad.

```suggestion
    apply Exists_or_inv in Hexists as [Hsent | Hreceived].
```

2022-02-08 22:45 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
>            fold (~ oracles i (s i) m).
```suggestion
```

2022-02-08 22:45 UTC, wkolowski commented on theories/VLSM/Core/Equivocation.v
> +  unfold can_emit; eauto.
```suggestion
    subst; cbn in Ht; unfold can_emit; eauto.
```

2022-02-09 07:56 UTC, traiansf commented on theories/VLSM/Core/Equivocation.v
> +      : oracle_stepwise_props selector' oracle.
I also agree, in principle, but this was again done to suit the indentation in the surrounding context.
I'll add another TODO, and add a proof engineering task in the issues list.

2022-02-09 15:50 UTC, bmmoore commented on theories/VLSM/Core/Equivocation/TraceWiseEquivocation.v
> +Local Instance equivocation_dec_tracewise
I agree that ltac in terms is *much* worse than `Program`, but I also prefer to avoid Program unless we're getting good use out of it's unique features, because it's not obvious what missing parts in the term each `Next Obligation` corresponds to. In this case I think the ltac-in-terms could easily be replaced with some `fun` that has an explicit application of `NoDup_enum`.

2022-02-14 17:10 UTC, wkolowski approved these changes
Looks good, I approve. But this doesn't mean that I don't have another 50 nitpicks : )

2022-02-14 17:10 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
>    assumption.
```suggestion
  eapply basic_projection_induces_friendliness; assumption.
```

2022-02-14 17:10 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +    - apply induced_sub_projection_transition_consistency_Some.
I see no point in adding additional indentation here. You should treat `Unshelve` like an ordinary subgoal-producing tactic, even though it is a command.

```suggestion
  - apply induced_sub_projection_transition_consistency_None.
  - apply composite_label_sub_projection_option_lift.
  - apply composite_state_sub_projection_lift.
  - apply induced_sub_projection_transition_consistency_Some.
```

2022-02-14 17:10 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +      rewrite sub_IM_state_update_eq, sub_element_state_eq.
A bullet is missing here.

```suggestion
    + rewrite sub_IM_state_update_eq, sub_element_state_eq.
```

2022-02-14 17:10 UTC, wkolowski commented on theories/VLSM/Core/SubProjectionTraces.v
> +      assumption.
```suggestion
    + rewrite sub_element_state_eq; assumption.
    + rewrite sub_element_state_neq by congruence.
      destruct (vs0 (IM i)); assumption.
```

2022-02-14 17:10 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections.v
> +  apply pre_loaded_vlsm_incl_relaxed. intuition.
```suggestion
  apply pre_loaded_vlsm_incl_relaxed; intuition.
```

2022-02-14 17:10 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections.v
> +  - cbv; apply pre_loaded_vlsm_incl. intuition.
```suggestion
  - apply pre_loaded_vlsm_incl_relaxed; intuition.
  - cbv; apply pre_loaded_vlsm_incl; intuition.
```

2022-02-16 08:39 UTC, merged