Finding duplicate filenames
runtimeverification/vlsm pull request #69
Opened 2022-07-22 09:23 UTC by DafinaTrufas

2022-07-22 10:00 UTC, palmskog commented
Let's post the current full table here:

| Number of occurrences | Filename | Paths |
|:----------------------|:---------|:------|
| 2 | Common.v | ./theories/VLSM/Core/Equivocators/Composition/Common.v  ./theories/VLSM/Core/Equivocators/Common.v |
| 2 | LimitedEquivocation.v | ./theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/LimitedEquivocation.v  ./theories/VLSM/Core/Equivocation/LimitedEquivocation.v |
| 2 | Projections.v | ./theories/VLSM/Core/Equivocators/Projections.v  ./theories/VLSM/Core/Equivocators/Composition/Projections.v |

2022-07-22 10:06 UTC, palmskog requested changes
This has the right idea, but please try to follow the pattern from the script on LOC ratios.

2022-07-22 10:06 UTC, palmskog commented on DUPLICATES.md
> +| Number of occurrences | Filename | Paths |
Can we make this into a task in `Makefile.coq.local` like for the ratios and `DUPLICATES.md`? As before, the problem with having this file checked in is that it will either become obsolete, or has to be updated/regenerated for each commit.

2022-07-22 10:06 UTC, palmskog commented on scripts/duplicates.sh
> +        find . -iname "$i" -exec $BASE/filenames.sh "{}" \; | sed 's/\t/\t | /g; s/^/| /g; s/$/ |/g'
Please find some way to send command in `filenames.sh` **in line**, that is, without calling an external script file. This way, we will only have one file to maintain. The current functionality in `filenames.sh` is trivial, so we'd like to avoid having a file with it, if possible.

2022-07-22 11:50 UTC, wkolowski requested changes
Besides addressing Karl's suggestions, please write some comments for `duplicates.sh`, so that people will have easier time when there's a need to revisit it.

2022-07-22 11:50 UTC, wkolowski commented on scripts/duplicates.sh
> +    done
```suggestion
#!/bin/sh
BASE=$(dirname $0)
echo "| Number of occurrences | Filename | Paths |"
echo "|:----------------------|:---------|:------|"
is_int() { test "$@" -eq "$@" 2> /dev/null; } 
DUPLICATES=$(find . -iname "*.v" -type f -printf "%f\n" | sort | uniq -cd)
for i in $DUPLICATES
do
  echo  -n " $i "
  find . -iname "$i" -exec $BASE/filenames.sh "{}" \; | sed 's/\t/\t | /g; s/^/| /g; s/$/ |/g'
  if ! is_int "$i"
  then 
    echo
  fi
done
```
Keep the script more compact - use 2 spaces for indentation instead of 4.

2022-07-25 09:40 UTC, palmskog reviewed
The code and Makefile task looks great now! 

But can you please remove the file `DUPLICATES.md` from the branch? Recall that we want to generate this file on command, rather than have it checked into version control.

2022-07-25 09:46 UTC, DafinaTrufas commented
> The code and Makefile task looks great now!
> 
> But can you please remove the file `DUPLICATES.md` from the branch? Recall that we want to generate this file on command, rather than have it checked into version control.

Oh, yes, I've forgotten to remove it.

2022-07-25 09:59 UTC, wkolowski requested changes
I'd like to see a few more changes, and don't forget to delete `DUPLICATES.md`.

2022-07-25 09:59 UTC, wkolowski commented on scripts/duplicates.sh
> +echo "|:----------------------|:---------|:------|"
I think printing right at the start of the script is not a good idea. Please move it a bit down, to right before the loop. I think it makes more sense that way.

2022-07-25 09:59 UTC, wkolowski commented on scripts/duplicates.sh
> +BASE=$(dirname $0)
This variable is not used below, what's the point of it?

2022-07-25 09:59 UTC, wkolowski commented on scripts/duplicates.sh
> +    echo  -n " $i " # the number of occurences / the filename
The comment is confusing, especially the `/` part in it.

2022-07-25 09:59 UTC, wkolowski commented on scripts/duplicates.sh
> +    if ! is_int "$i" # if the value of variable i at the current iteration is a string (filename), move on a new line
This is confusing, you write `! is_int`, which reads like "is not int", but then you say you're testing whether `$i` is a string/filename.

Can you refactor `is_int` to something like `is_filename`?

2022-07-25 10:48 UTC, DafinaTrufas commented on scripts/duplicates.sh
> +BASE=$(dirname $0)
I was initially using it and I've forgotten to remove it after I made some changes.

2022-07-25 10:51 UTC, DafinaTrufas commented on scripts/duplicates.sh
> +    if ! is_int "$i" # if the value of variable i at the current iteration is a string (filename), move on a new line
By "is not int", I meant "is string". But yes, I will rename the function as you suggested.

2022-07-25 10:53 UTC, DafinaTrufas commented on scripts/duplicates.sh
> +    if ! is_int "$i" # if the value of variable i at the current iteration is a string (filename), move on a new line
By "is not int", I meant "is string" (which means that it's a filename). The function tests whether the value of a variable is of type int, so I don't think that renaming it to "is_filename" would work.

2022-07-25 11:00 UTC, DafinaTrufas commented on scripts/duplicates.sh
> +    if ! is_int "$i" # if the value of variable i at the current iteration is a string (filename), move on a new line
I tried to fix it, by making that comment a bit more explicit. Please tell me if now it's all right!

2022-07-25 13:13 UTC, wkolowski commented on scripts/duplicates.sh
> +    if ! is_int "$i" # if the value of variable i at the current iteration is a string (filename), move on a new line
@DafinaTrufas

I meant that you should define a function `is_filename` that would be equivalent to `! is_int ...`.

Then you could write `if is_filename "$i"`, which would be much more readable. Is this possible in bash?

2022-07-25 13:26 UTC, DafinaTrufas commented on scripts/duplicates.sh
> +    if ! is_int "$i" # if the value of variable i at the current iteration is a string (filename), move on a new line
I don't know, but I will search for it.

2022-07-25 13:28 UTC, wkolowski requested changes
I think the rendering of the table is broken. There is no pipe `|` --between the number of occurrences and the filename-- before the number of occurrences, right at the start of a new line. Also, newline seems to be missing from the end. Please fix this.

2022-07-25 13:36 UTC, wkolowski commented
@DafinaTrufas

Also, I think the file paths are concatenated together. Could you make sure they are separated with `<br>`? (This will make them appear on separate lines).

2022-07-25 14:09 UTC, DafinaTrufas commented
> 
the problem is that, initially, I've fixed the table rendering by manually editing the Markdown file. And now, I don't manage to fix it by commands in the script.

2022-07-25 15:41 UTC, wkolowski requested changes
Looks like you got some kind of reversion, as the table header is back at the top, where you previously put it right above the loop.

Also, I see you deleted the `#[local]` attribute from `Forall_True`. Looks like your commit got polluted from your axiom diagnostics changes.

2022-07-25 15:41 UTC, wkolowski commented on scripts/duplicates.sh
> +  done
Looks like the final newline is missing.

2022-07-25 15:41 UTC, wkolowski commented on theories/VLSM/Lib/TopSort.v
> +Lemma Forall_True : forall l : list A, Forall (fun _ => True) l.
You should not delete this. @palmskog suggested doing this only for the purpose of making `axiom-diagnostics.sh` work, but I am now taking care of that. Please remove this change.

2022-07-25 15:43 UTC, wkolowski commented on scripts/duplicates.sh
> +BASE=$(dirname $0)
It seems you deleted this line, but it's back there.

2022-07-25 16:32 UTC, wkolowski approved these changes
I think it is ok now.

Please don't merge, I want to do a final refactoring.

2022-07-25 16:33 UTC, DafinaTrufas commented
> I think it is ok now.
> 
> Please don't merge, I want to do a final refactoring.

Sure! I wait for you to tell me when I can merge.

2022-07-25 17:45 UTC, wkolowski approved these changes

2022-07-25 17:52 UTC, palmskog approved these changes

2022-07-25 17:59 UTC, merged