Purge the Preamble from unused and useless definitions and lemmas
runtimeverification/vlsm pull request #77
Opened 2022-07-28 20:51 UTC by wkolowski

2022-08-01 11:05 UTC, traiansf approved these changes
I have nothing against it.

2022-08-03 09:24 UTC, palmskog requested changes
Looks good in general, but please address comments.

2022-08-03 09:24 UTC, palmskog commented on theories/VLSM/Lib/Preamble.v
> -Qed.
This looks like a useful lemma to have around - it's nontrivial for most Coq users, and can be useful when reasoning about equality, as shown in the forum link. So I think both the lemma and the link should stay.

2022-08-03 09:24 UTC, palmskog commented on theories/VLSM/Lib/Temporal.v
> +    assert (∀ n : A, ¬ Eventually (Forever (λ s : Stream A, hd s = n)) s) by firstorder.
I don't the see the need to use UTF8 here.
```suggestion
    assert (forall n : A, ~ Eventually (Forever (fun s : Stream A, hd s = n)) s) by firstorder.
```

2022-08-03 11:09 UTC, wkolowski commented on theories/VLSM/Lib/Temporal.v
> +    assert (∀ n : A, ¬ Eventually (Forever (λ s : Stream A, hd s = n)) s) by firstorder.
Hmm, I think they got there by copy-pasting.

2022-08-03 11:27 UTC, palmskog approved these changes

2022-08-03 12:03 UTC, merged