Homogenizing Require-Imports
runtimeverification/vlsm pull request #82
Opened 2022-08-04 10:49 UTC by DafinaTrufas

2022-08-04 10:53 UTC, DafinaTrufas commented
I found it easier to create a new branch and restart the whole process, rather than resolving the conflicts caused accidentally in the old one. Sorry for taking so long to fix it! I will address Karl's review about `Coq` imports soon.

2022-08-04 11:43 UTC, palmskog requested changes
Looks good in general, but please take a look at the comments and suggestions.

2022-08-04 11:43 UTC, palmskog commented on theories/VLSM/Core/Composition.v
> +This module providesFrom Coq Require Import definitions for composite VLSMs and their projections
This looks like an unintended modification by a script. Please roll back.

2022-08-04 11:43 UTC, palmskog commented on theories/VLSM/Core/VLSM.v
> +InFrom Coq Require Import it is defined as a Class taking <<message>> as parameter and having
This should be rolled back.

2022-08-04 11:43 UTC, palmskog commented on theories/VLSM/Lib/ListSetExtras.v
> +(* TODO(palmskog): consider submitting a PR toFrom Coq Require Import s stdlib. *)
Another roll back.

2022-08-04 11:43 UTC, palmskog commented on theories/VLSM/Lib/Preamble.v
> +(* TODO(traian): remove these definitions and use the standardFrom stdpp Require Import ones instead.*)
Another roll back.

2022-08-04 11:43 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/SimulatingFree/SimulatingFree.v
> +From Coq Require Import Logic.FinFun Logic.FunctionalExtensionality.
```suggestion
From Coq Require Import FinFun FunctionalExtensionality.
```

2022-08-04 11:43 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/SimulatingFree/FullReplayTraces.v
> +From Coq Require Import Logic.FinFun Program.Program.
```suggestion
From Coq Require Import FinFun Program.
```

2022-08-04 11:43 UTC, palmskog commented on theories/VLSM/Core/VLSMProjections.v
> +From VLSM.Core Require Export VLSMProjections.VLSMEmbedding VLSMProjections.VLSMInclusion VLSMProjections.VLSMEquality.
Looks like some paths are overspecified here compared to the original, see also elsewhere.
```suggestion
From VLSM.Core Require Export VLSMPartialProjection VLSMTotalProjection.
From VLSM.Core Require Export VLSMEmbedding VLSMInclusion VLSMEquality.
```

2022-08-04 11:43 UTC, palmskog commented on theories/VLSM/Lib/Preamble.v
> +From Coq Require Export Tactics.
This special case is conventional to spell out.
```suggestion
From Coq Require Export Program.Tactics.
```

2022-08-04 13:26 UTC, palmskog requested changes
Looks better, but some polish is still needed, please see comments

2022-08-04 13:26 UTC, palmskog commented on theories/VLSM/Core/Equivocation/WitnessedEquivocation.v
> +From VLSM.Core Require Import Equivocation.NoEquivocation Equivocation.FixedSetEquivocation Equivocation.TraceWiseEquivocation.
```suggestion
From VLSM.Core Require Import NoEquivocation FixedSetEquivocation TraceWiseEquivocation.
```

2022-08-04 13:26 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/EquivocatorsComposition.v
> +From Coq Require Import Logic.FinFun Logic.FunctionalExtensionality.
```suggestion
From Coq Require Import FinFun FunctionalExtensionality.
```

2022-08-04 13:26 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/EquivocatorsCompositionProjections.v
> +From Coq Require Import Logic.FinFun Logic.FunctionalExtensionality.
```suggestion
From Coq Require Import FinFun FunctionalExtensionality.
```

2022-08-04 13:26 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/EquivocatorsCompositionProjections.v
> +From VLSM.Core Require Import Equivocators.Equivocators Equivocators.EquivocatorsProjections Equivocators.Composition.EquivocatorsComposition Equivocators.MessageProperties.
Please split this one across two lines to avoid length concerns.

2022-08-04 13:26 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/FixedEquivocationSimulation.v
> +    clear. (* TODO: replace withFrom stdpp Require Import list.last_lookup once it becomes available *)
Please roll back the changes here.

2022-08-04 13:26 UTC, palmskog commented on theories/VLSM/Lib/TraceProperties.v
> +From Coq Require Import Equality.
This is another special case.
```suggestion
From Coq Require Import Program.Equality.
```

2022-08-04 15:12 UTC, palmskog approved these changes
Looks mergeable now, but two final nitpicks.

2022-08-04 15:12 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/LimitedStateEquivocation.v
> +From Coq Require Import Logic.FinFun Reals.Reals.
```suggestion
From Coq Require Import FinFun Reals.
```

2022-08-04 15:12 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/LimitedEquivocationSimulation.v
> +From Coq Require Import Logic.FinFun Reals.Reals.
```suggestion
From Coq Require Import FinFun Reals.
```

2022-08-05 11:59 UTC, wkolowski reviewed
Looks ok, but please reply to my suggestions.

2022-08-05 11:59 UTC, wkolowski commented on theories/VLSM/Core/ByzantineTraces/FixedSetByzantineTraces.v
> +From VLSM.Core Require Import Validator Equivocation EquivocationProjections Equivocation.NoEquivocation Equivocation.FixedSetEquivocation.
Maybe you could split these `Equivocation.` into a separate line `From VSLM.Core.Equivocation Require Import ...`.

2022-08-05 11:59 UTC, wkolowski commented on theories/VLSM/Core/Equivocation/MsgDepLimitedEquivocation.v
> +From VLSM.Core Require Import Equivocation.MsgDepFixedSetEquivocation Equivocation.TraceWiseEquivocation.
I'm not sure what's the logic behind this PR, but isn't this a change in the opposite direction from what we want?

2022-08-05 11:59 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/EquivocatorsCompositionProjections.v
> +From VLSM.Core Require Import Equivocators.Composition.EquivocatorsComposition Equivocators.MessageProperties.
Again.

2022-08-05 11:59 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/LimitedEquivocation/LimitedStateEquivocation.v
> +From Coq Require Import Logic.FinFun Reals.Reals.
I think you should go over all imports again and make sure imports from Coq's standard library are not written out in full, like @palmskog suggested.

2022-08-05 11:59 UTC, wkolowski commented on theories/VLSM/Core/VLSMProjections.v
> +From VLSM.Core Require Export VLSMEmbedding VLSMInclusion VLSMEquality.
Again, why remove the `.VLSMProjections` suffix from the `From`?

2022-08-06 06:55 UTC, DafinaTrufas commented on theories/VLSM/Core/Equivocation/MsgDepLimitedEquivocation.v
> +From VLSM.Core Require Import Equivocation.MsgDepFixedSetEquivocation Equivocation.TraceWiseEquivocation.
Then it's possible that I misunderstood the pattern of the imports we want to achieve.

2022-08-06 09:52 UTC, wkolowski commented on theories/VLSM/Core/Equivocation/MsgDepLimitedEquivocation.v
> +From VLSM.Core Require Import Equivocation.MsgDepFixedSetEquivocation Equivocation.TraceWiseEquivocation.
I don't know either what's desired, but @palmskog probably does.

2022-08-06 09:58 UTC, palmskog commented on theories/VLSM/Core/Equivocation/MsgDepLimitedEquivocation.v
> +From VLSM.Core Require Import Equivocation.MsgDepFixedSetEquivocation Equivocation.TraceWiseEquivocation.
We can come up with some improved scheme later, but for this PR, I wanted to homogenize to `From VLSM.X Require Import ...`. 

Yes, this has the consequence that some `From VLSM.X.Y Require Import ..` become more verbose, but consistency is a priority for now.

2022-08-08 07:44 UTC, merged