A tactic which automates reasoning about the state_update function
runtimeverification/vlsm pull request #87
Opened 2022-08-12 12:43 UTC by wkolowski

I noticed that there are some clear patterns when reasoning about the `state_update` function from `Composition.v`. Namely, if the indices are equal, we `rewrite state_update_eq`, when they are not we `rewrite state_update_neq` and when we don't know, we do `destruct (decide (i = j)); subst` and then we `rewrite` accordingly.

This often causes the nesting level of the proof to increase by 1, which makes proofs less readable. So maybe it's a good idea to have a tactic for this?

2022-08-15 10:55 UTC, palmskog requested changes
I'm sympathetic to the idea of domain-specific rewriting automation. However, the custom tactic is basically just applying rewrites. A more disciplined and maintainable way to do this is to use *named* rewriting databases (`Hint Rewrite my_eq : my_db`) and for example the [autorewrite](https://coq.inria.fr/refman/proofs/automatic-tactics/auto.html#coq:tacn.autorewrite) tactic.

2022-08-15 11:58 UTC, wkolowski commented
@palmskog Yes, `autorewrite` seems a bit better here, as in later modules there are some new lemmas about particular incarnations of `state_update`. I will refactor this refactoring to use it, but it can make this refactoring take a lot more time.

2022-08-15 13:28 UTC, palmskog commented
@wkolowski since this looks like pure refactoring PR (no new results), it's fine by me if it takes time (and it shouldn't affect anything else). You might consider marking the PR as a WIP until you change it to use rewriting databases.

2022-08-16 20:53 UTC, palmskog requested changes
The rewrite database and the `state_update_simpl` tactic is good. But I completely disagree about the `state_update` tactic. In particular, several easy proofs were given *more* automation.

2022-08-16 20:53 UTC, palmskog commented on theories/VLSM/Core/Composition.v
> +  A nice little tactic for dealing with [state_update].
```suggestion
  Hint database and tactic for dealing with updates and lifting via [state_update].
```

2022-08-16 20:53 UTC, palmskog commented on theories/VLSM/Core/Composition.v
> +
I don't see the point of introducing this tactic. It basically just composes two standard tactic calls with an automation tactic. I think this only obscures what is going on in proofs and will make them harder to maintain.
```suggestion
```

2022-08-16 20:53 UTC, palmskog commented on theories/VLSM/Core/Composition.v
> +  extensionality j; state_update i j; [done |].
Here is a case in point of why the `state_update` tactic is more trouble than it's worth: instead of a regular case analysis with a substitution, we are now running a powerful and possibly long-running tactic under the hood.

2022-08-17 12:13 UTC, wkolowski commented on theories/VLSM/Core/Composition.v
> +
Ok, maybe you are right, especially that `state_update_simpl` is not a succeed-or-fail kind of tactic. I'll remove `state_update i j`.

2022-08-17 13:04 UTC, palmskog requested changes
This is a clear step in the right direction, but at the minimum, all `Hint`s must have locality. I also worry a lot about the size of rewrite databases.

2022-08-17 13:04 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/EquivocatorsCompositionProjections.v
> +Hint Unfold equivocator_descriptors_update : state_update.
Please ensure that all new `Hint` have a locality (probably `#[export]` for all of them).
```suggestion
#[export] Hint Unfold equivocator_descriptors_update : state_update.
```

2022-08-17 13:04 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Equivocators.v
> +Hint Rewrite @equivocator_state_update_size : state_update.
It worries me a lot to see a database with 20+ rewriting lemmas, this can lead to significant slowdowns with `autorewrite` (recall that it tries *everything* repeatedly). How about instead creating different databases for each "type" of update, such as `equivocator_state_update`?

2022-08-17 13:09 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/EquivocatorsCompositionProjections.v
> +Hint Unfold equivocator_descriptors_update : state_update.
Umm, this is inside a `Section`, so I guess your locality is incorrect here. If I recall correctly, all `Hint`s I added outside `Section`s are `#[export]`, and the ones inside sections have no locality given.

2022-08-17 13:13 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Composition/EquivocatorsCompositionProjections.v
> +Hint Unfold equivocator_descriptors_update : state_update.
But if it's indeed inside a section, you should add `#[local]` to indicate that. The point is that we want explicit locality for all `Hint`, no matter if it's `#[export]` or not.

2022-08-17 13:18 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Composition/EquivocatorsCompositionProjections.v
> +Hint Unfold equivocator_descriptors_update : state_update.
Ok, I'll add them.

2022-08-17 13:33 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Equivocators.v
> +Hint Rewrite @equivocator_state_update_size : state_update.
14 of these 20+ are a matter of a single file (`Equivocators.v`), so it's probably less bad than it sounds. Also, from my experience, there are maybe 1 or 2 places where there was some slowdown, but these were chains of 10 or 20 tactics which probably should be refactored anyway.

Also, I think the separation might not be that easy to achieve, since these various flavors of `state_update` are somewhat interdependent. Maybe we should just have a separate tactic for `equivocator_state_update` if that's possible?

2022-08-17 13:41 UTC, palmskog commented on theories/VLSM/Core/Equivocators/Equivocators.v
> +Hint Rewrite @equivocator_state_update_size : state_update.
Yes, the main issue might be with equivocator state updates. I think a separate `equivocator_state_update_simpl` tactic might be a good idea, to separate at least to some extent by the domain. Recall that one can configure `autorewrite` with multiple databases.

2022-08-17 15:11 UTC, palmskog approved these changes
I think it all looks reasonable now, even if the duplicated hints (local vs export) are a bit unfortunate.

2022-08-17 15:57 UTC, wkolowski commented on theories/VLSM/Core/Equivocators/Equivocators.v
> +#[local] Hint Rewrite @equivocator_state_update_size : equivocator_state_update.
Right, the manual proofs look shorter than the `Hint` base needed to automate them.

2022-08-17 16:25 UTC, merged

2022-08-22 07:10 UTC, traiansf commented
A quite nice and elegant solution. Thanks @wkolowski  and @palmskog for making it happen.