Addressing part of the reviews regarding the script
runtimeverification/vlsm pull request #93
Opened 2022-08-19 08:31 UTC by DafinaTrufas

2022-08-19 09:05 UTC, DafinaTrufas commented
Now I think the only review I didn't address at all is the one regarding the case when the `max-consecutive-newlines` argument isn't a number. I'm not sure how to deal with this case.

2022-08-19 12:42 UTC, wkolowski requested changes

2022-08-19 12:42 UTC, wkolowski commented on scripts/strip_newlines.py
> +
It's a bit ironic that you have double newlines in a script supposed to remove them :)

2022-08-19 12:42 UTC, wkolowski commented on scripts/strip_newlines.py
> +    max_consecutive_newlines = int(sys.argv[1])
If I do `int("asd")` in Python 3 shell, I get an exception:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'asd'
```

The exception can be caught and handled more gracefully:

```python
try:
  int("asd")
except ValueError:
  print("The argument must a positive number!")
```

Read https://docs.python.org/3/tutorial/errors.html to learn more.

2022-08-19 12:45 UTC, DafinaTrufas commented on scripts/strip_newlines.py
> +
Oh, I will fix that.

2022-08-19 12:46 UTC, DafinaTrufas commented on scripts/strip_newlines.py
> +    max_consecutive_newlines = int(sys.argv[1])
Ok, I'll handle this exception.

2022-08-19 13:04 UTC, wkolowski approved these changes

2022-08-19 14:37 UTC, wkolowski requested changes
Please address my suggestions. Also, what is this binary `.pyc` file?

2022-08-19 14:37 UTC, wkolowski commented on TOOLS.md
> +## Striping newlines
I think you made a typo there: https://grammarist.com/usage/stripedstriping-vs-strippedstripping

2022-08-19 14:37 UTC, wkolowski commented on TOOLS.md
> +In case you pass a negative number as argument, the content will remain unchanged, and if the argument you pass is `0`, then all strings of consecutive newlines will be replaced by a single space.
You meant "newline" there, I guess?

```suggestion
In case you pass a negative number as argument, the content will remain unchanged, and if the argument you pass is `0`, then all strings of consecutive newlines will be replaced by a single newline.
```

2022-08-19 14:37 UTC, wkolowski commented on TOOLS.md
> +python scripts/strip-newlines.py 2
I think this is confusing. The argument is 2, but the effect is that there is at most one consecutive newline. Maybe refactor so that the argument is `max`, not `max + 1`?

2022-08-19 14:37 UTC, wkolowski commented on scripts/strip_newlines.py
> +#!/usr/bin/env python
Looks like the script is doubled. Please delete one of them.

2022-08-19 18:56 UTC, DafinaTrufas commented on TOOLS.md
> +In case you pass a negative number as argument, the content will remain unchanged, and if the argument you pass is `0`, then all strings of consecutive newlines will be replaced by a single space.
This information is taken from the `coq-tools` script which I imported to my script.

2022-08-19 18:56 UTC, DafinaTrufas commented on TOOLS.md
> +In case you pass a negative number as argument, the content will remain unchanged, and if the argument you pass is `0`, then all strings of consecutive newlines will be replaced by a single space.
And there was saying `space`, not `newline`.

2022-08-19 18:59 UTC, DafinaTrufas commented on TOOLS.md
> +python scripts/strip-newlines.py 2
Again, I maintained the idea from the `coq-tools` script. This is the explanation from there:
```If max_consecutive_newlines > 0, all strings of consecutive
    newlines in excess of max_consecutive_newlines are replaced by
    max_consecutive_newlines newlines.```

2022-08-19 19:02 UTC, DafinaTrufas commented
Regarding the `.pyc` file, that is a binary file which is automatically generated for the `.py` file.

2022-08-19 19:39 UTC, wkolowski commented
@DafinaTrufas It's probably not a good idea to commit autogenerated binary files to the repo. Please remove it.

2022-08-22 11:14 UTC, palmskog approved these changes
This looks good to me now.

2022-08-22 11:46 UTC, wkolowski approved these changes
It's probably good enough now.

2022-08-22 12:41 UTC, merged